project:
  type: manuscript
  output-dir: _output
  resources:
    - "_*.qmd"

manuscript:
  article: capstone.qmd
  notebooks: []

format:
  html:
    embed-resources: true
    notebook-view: false
    css: styles.css
    include-after-body: caption-bold.html
    theme:
      light: lightly
      dark: darkly

execute:
  echo: false
  warning: false
  freeze: auto

jupyter: python3