project:
  type: manuscript
  output-dir: _output

resources:
  - "_*.qmd"

manuscript:
  article: capstone.qmd

format:
  html:
    embed-resources: true
    notebook-view: false
    theme:
      light: lightly
      dark: darkly
    mermaid:
      theme: neutral

execute:
  echo: false
  warning: false
  freeze: auto

jupyter: python3
