<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>How Job Automatability Relates to County Affordability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-bc185b5c5bdbcb35c2eb49d8a876ef70.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-1c59215f878e034bd7426c637fa661ac.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="How Job Automatability Relates to County Affordability">
<meta name="citation_author" content="Chris Bell">
<meta name="citation_author" content="Julian Pacheco">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=A guide to backward paper writing for the data sciences;,citation_abstract=Summary In this perspective, we outline a set of best practices for the planning, writing, and revision of scientific papers and other forms of professional communication in the data sciences. We propose a backward approach that begins with clearly identifying the scientific and professional goals motivating the work, followed by a purposeful mapping from those goals to each section of a paper. This approach is motivated by the conviction that manuscript writing can be more effective, efficient, creative, and even enjoyable—particularly for early-career researchers—when the overarching goals of the paper and its individual components are clearly mapped out.;,citation_author=Jon Zelner;,citation_author=Kelly Broen;,citation_author=Ella August;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/pii/S2666389921003068;,citation_issue=3;,citation_doi=10.1016/j.patter.2021.100423;,citation_issn=2666-3899;,citation_volume=3;,citation_journal_title=Patterns;">
<meta name="citation_reference" content="citation_title=The skill content of recent technological change: An empirical exploration;,citation_abstract=Summary We apply an understanding of what computers do to study how computerization alters job skill demands. We argue that computer capital (1) substitutes for workers in performing cognitive and manual tasks that can be accomplished by following explicit rules; and (2) complements workers in performing nonroutine problem-solving and complex communications tasks. Provided these tasks are imperfect substitutes, our model implies measurable changes in the composition of job tasks, which we explore using representative data on task input for 1960 to 1998. We find that within industries, occupations and education groups, computerization is associated with reduced labor input of routine manual and routine cognitive tasks and increased labor input of nonroutine cognitive tasks. Translating task shifts into education demand, the model can explain sixty percent of the estimated relative demand shift favoring college labor during 1970 to 1998. Task changes within nominally identical occupations account for almost half of this impact.;,citation_author=David H. Autor;,citation_author=Frank Levy;,citation_author=Richard J. Murnane;,citation_publication_date=2003;,citation_cover_date=2003;,citation_year=2003;,citation_fulltext_html_url=https://academic.oup.com/qje/article/118/4/1279/1925105;,citation_issue=4;,citation_doi=10.1162/003355303322552801;,citation_issn=0033-5533;,citation_volume=118;,citation_journal_title=The Quarterly Journal of Economics;">
<meta name="citation_reference" content="citation_title=The growth of low-skill service jobs and the polarization of the US labor market;,citation_abstract=Summary We offer a unified analysis of the growth of low-skill service occupations between 1980 and 2005 and the concurrent polarization of US employment and wages. We hypothesize that polarization stems from the interaction between consumer preferences, which favor variety over specialization, and the falling cost of automating routine, codifiable job tasks. Applying a spatial equilibrium model, we corroborate four implications of this hypothesis. Local labor markets that specialized in routine tasks differentially adopted information technology, reallocated low-skill labor into service occupations (employment polarization), experienced earnings growth at the tails of the distribution (wage polarization), and received inflows of skilled labor.;,citation_author=David H. Autor;,citation_author=David Dorn;,citation_publication_date=2013;,citation_cover_date=2013;,citation_year=2013;,citation_fulltext_html_url=https://www.aeaweb.org/articles?id=10.1257/aer.103.5.1553;,citation_issue=5;,citation_doi=10.1257/aer.103.5.1553;,citation_issn=0002-8282;,citation_volume=103;,citation_journal_title=American Economic Review;">
<meta name="citation_reference" content="citation_title=Skills, tasks and technologies: Implications for employment and earnings;,citation_abstract=Summary A central organizing framework of the voluminous recent literature studying changes in the returns to skills and the evolution of earnings inequality is what we refer to as the canonical model, which elegantly and powerfully operationalizes the supply and demand for skills by assuming two distinct skill groups that perform two different and imperfectly substitutable tasks or produce two imperfectly substitutable goods. Technology is assumed to take a factor-augmenting form, which, by complementing either high or low skill workers, can generate skill biased demand shifts. In this paper, we argue that despite its notable successes, the canonical model is largely silent on a number of central empirical developments of the last three decades, including: (1) significant declines in real wages of low skill workers, particularly low skill males; (2) non-monotone changes in wages at different parts of the earnings distribution during different decades; (3) broad-based increases in employment in high skill and low skill occupations relative to middle skilled occupations (i.e., job “polarization’’); (4) rapid diffusion of new technologies that directly substitute capital for labor in tasks previously performed by moderately skilled workers; and (5) expanding offshoring in opportunities, enabled by technology, which allow foreign labor to substitute for domestic workers specific tasks. Motivated by these patterns, we argue that it is valuable to consider a richer framework for analyzing how recent changes in the earnings and employment distribution in the United States and other advanced economies are shaped by the interactions among worker skills, job tasks, evolving technologies, and shifting trading opportunities. We propose a tractable task-based model in which the assignment of skills to tasks is endogenous and technical change may involve the substitution of machines for certain tasks previously performed by labor. We further consider how the evolution of technology in this task-based setting may be endogenized. We show how such a framework can be used to interpret several central recent trends, and we also suggest further directions for empirical exploration.;,citation_author=Daron Acemoglu;,citation_author=David Autor;,citation_editor=David Card;,citation_editor=Orley Ashenfelter;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/pii/S0169721811024105;,citation_doi=10.1016/S0169-7218(11)02410-5;,citation_issn=1573-4463;,citation_volume=4;,citation_inbook_title=Handbook of labor economics;">
<meta name="citation_reference" content="citation_title=Combining satellite imagery and machine learning to predict poverty;,citation_abstract=Summary Reliable data on economic livelihoods remain scarce in the developing world, hampering efforts to study these outcomes and to design policies that improve them. Here we demonstrate an accurate, inexpensive, and scalable method for estimating consumption expenditure and asset wealth from high-resolution satellite imagery. Using survey and satellite data from five African countries—Nigeria, Tanzania, Uganda, Malawi, and Rwanda—we show how a convolutional neural network can be trained to identify image features that can explain up to 75;,citation_author=Neal Jean;,citation_author=Marshall Burke;,citation_author=Michael Xie;,citation_author=W. Matthew Davis;,citation_author=David B. Lobell;,citation_author=Stefano Ermon;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_fulltext_html_url=https://www.science.org/doi/10.1126/science.aaf7894;,citation_issue=6301;,citation_doi=10.1126/science.aaf7894;,citation_issn=0036-8075;,citation_volume=353;,citation_journal_title=Science;">
<meta name="citation_reference" content="citation_title=Automation in everyday life;,citation_author=Aaron Smith;,citation_author=Monica Anderson;,citation_publication_date=2017-10;,citation_cover_date=2017-10;,citation_year=2017;,citation_fulltext_html_url=https://www.pewresearch.org/internet/2017/10/04/automation-in-everyday-life/;,citation_technical_report_institution=Pew Research Center;">
<meta name="citation_reference" content="citation_title=More U.S. Workers fear technology making their jobs obsolete;,citation_author=Lydia Saad;,citation_publication_date=2023-09;,citation_cover_date=2023-09;,citation_year=2023;,citation_fulltext_html_url=https://news.gallup.com/poll/510551/workers-fear-technology-making-jobs-obsolete.aspx;,citation_technical_report_institution=Gallup;">
<meta name="citation_reference" content="citation_title=American community survey 1-year estimates;,citation_author=U.S. Census Bureau;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_publisher=https://www.census.gov/programs-surveys/acs;">
<meta name="citation_reference" content="citation_title=Core based statistical area delineation files;,citation_author=U.S. Census Bureau;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_publisher=https://www.census.gov/geographies/reference-files/time-series/demo/metro-micro/delineation-files.html;">
<meta name="citation_reference" content="citation_title=Regional price parities by state and metro area;,citation_author=U.S. Bureau of Economic Analysis;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_publisher=https://www.bea.gov/data/prices-inflation/regional-price-parities-state-and-metro-area;">
<meta name="citation_reference" content="citation_title=Local area unemployment statistics;,citation_author=U.S. Bureau of Labor Statistics;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_publisher=https://www.bls.gov/lau/;">
<meta name="citation_reference" content="citation_title=Occupational employment and wage statistics;,citation_author=U.S. Bureau of Labor Statistics;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_publisher=https://www.bls.gov/oes/;">
<meta name="citation_reference" content="citation_title=O*NET database;,citation_author=National Center for O*NET Development, U.S. Department of Labor;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_publisher=https://www.onetcenter.org/database.html;">
</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How Job Automatability Relates to County Affordability</h1>
            <p class="subtitle lead">Subtitle</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
        
        <div class="quarto-title-meta">

                <div>
            <div class="quarto-title-meta-heading">Authors</div>
            <div class="quarto-title-meta-contents">
                        <p>Chris Bell </p>
                        <p>Julian Pacheco </p>
                      </div>
          </div>
                
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-background" id="toc-sec-background" class="nav-link" data-scroll-target="#sec-background"><span class="header-section-number">2</span> Background and Related Work</a></li>
  <li><a href="#sec-data" id="toc-sec-data" class="nav-link" data-scroll-target="#sec-data"><span class="header-section-number">3</span> Data</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection"><span class="header-section-number">3.1</span> Data collection</a></li>
  <li><a href="#measuring-task-structure" id="toc-measuring-task-structure" class="nav-link" data-scroll-target="#measuring-task-structure"><span class="header-section-number">3.2</span> Measuring task structure</a></li>
  <li><a href="#measuring-affordability" id="toc-measuring-affordability" class="nav-link" data-scroll-target="#measuring-affordability"><span class="header-section-number">3.3</span> Measuring affordability</a></li>
  <li><a href="#control-variables" id="toc-control-variables" class="nav-link" data-scroll-target="#control-variables"><span class="header-section-number">3.4</span> Control variables</a></li>
  <li><a href="#storage-and-organization" id="toc-storage-and-organization" class="nav-link" data-scroll-target="#storage-and-organization"><span class="header-section-number">3.5</span> Storage and organization</a></li>
  <li><a href="#the-analytical-dataset" id="toc-the-analytical-dataset" class="nav-link" data-scroll-target="#the-analytical-dataset"><span class="header-section-number">3.6</span> The analytical dataset</a></li>
  </ul></li>
  <li><a href="#sec-analysis" id="toc-sec-analysis" class="nav-link" data-scroll-target="#sec-analysis"><span class="header-section-number">4</span> Analysis</a>
  <ul class="collapse">
  <li><a href="#panel-regression" id="toc-panel-regression" class="nav-link" data-scroll-target="#panel-regression"><span class="header-section-number">4.1</span> Panel regression</a></li>
  <li><a href="#validation-before-modeling" id="toc-validation-before-modeling" class="nav-link" data-scroll-target="#validation-before-modeling"><span class="header-section-number">4.2</span> Validation before modeling</a></li>
  <li><a href="#specification-diagnostics" id="toc-specification-diagnostics" class="nav-link" data-scroll-target="#specification-diagnostics"><span class="header-section-number">4.3</span> Specification diagnostics</a></li>
  <li><a href="#log-respecification" id="toc-log-respecification" class="nav-link" data-scroll-target="#log-respecification"><span class="header-section-number">4.4</span> Log respecification</a></li>
  <li><a href="#variance-decomposition" id="toc-variance-decomposition" class="nav-link" data-scroll-target="#variance-decomposition"><span class="header-section-number">4.5</span> Variance decomposition</a></li>
  <li><a href="#predictive-modeling" id="toc-predictive-modeling" class="nav-link" data-scroll-target="#predictive-modeling"><span class="header-section-number">4.6</span> Predictive Modeling</a>
  <ul class="collapse">
  <li><a href="#feature-set-and-reference-categories" id="toc-feature-set-and-reference-categories" class="nav-link" data-scroll-target="#feature-set-and-reference-categories"><span class="header-section-number">4.6.1</span> Feature set and reference categories</a></li>
  <li><a href="#year-and-state-dummies" id="toc-year-and-state-dummies" class="nav-link" data-scroll-target="#year-and-state-dummies"><span class="header-section-number">4.6.2</span> Year and state dummies</a></li>
  <li><a href="#collinearity-check" id="toc-collinearity-check" class="nav-link" data-scroll-target="#collinearity-check"><span class="header-section-number">4.6.3</span> Collinearity check</a></li>
  <li><a href="#traintest-split-grouped-by-county" id="toc-traintest-split-grouped-by-county" class="nav-link" data-scroll-target="#traintest-split-grouped-by-county"><span class="header-section-number">4.6.4</span> Train/test split (grouped by county)</a></li>
  <li><a href="#linear-regression-baseline-vs.-full-model" id="toc-linear-regression-baseline-vs.-full-model" class="nav-link" data-scroll-target="#linear-regression-baseline-vs.-full-model"><span class="header-section-number">4.6.5</span> Linear regression: baseline vs.&nbsp;full model</a></li>
  <li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest"><span class="header-section-number">4.6.6</span> Random Forest</a></li>
  <li><a href="#simple-neural-net" id="toc-simple-neural-net" class="nav-link" data-scroll-target="#simple-neural-net"><span class="header-section-number">4.6.7</span> Simple neural net</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation"><span class="header-section-number">4.6.8</span> Cross validation</a></li>
  </ul></li>
  <li><a href="#wrap-up-summary" id="toc-wrap-up-summary" class="nav-link" data-scroll-target="#wrap-up-summary"><span class="header-section-number">4.7</span> Wrap-up summary</a></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results"><span class="header-section-number">5</span> Results</a>
  <ul class="collapse">
  <li><a href="#where-affordability-is-strained" id="toc-where-affordability-is-strained" class="nav-link" data-scroll-target="#where-affordability-is-strained"><span class="header-section-number">5.1</span> Where affordability is strained</a></li>
  <li><a href="#task-groups-and-affordability" id="toc-task-groups-and-affordability" class="nav-link" data-scroll-target="#task-groups-and-affordability"><span class="header-section-number">5.2</span> Task groups and affordability</a></li>
  <li><a href="#nonlinearity" id="toc-nonlinearity" class="nav-link" data-scroll-target="#nonlinearity"><span class="header-section-number">5.3</span> Nonlinearity</a></li>
  <li><a href="#what-matters-most" id="toc-what-matters-most" class="nav-link" data-scroll-target="#what-matters-most"><span class="header-section-number">5.4</span> What matters most</a></li>
  <li><a href="#stability-over-time" id="toc-stability-over-time" class="nav-link" data-scroll-target="#stability-over-time"><span class="header-section-number">5.5</span> Stability over time</a></li>
  <li><a href="#robustness" id="toc-robustness" class="nav-link" data-scroll-target="#robustness"><span class="header-section-number">5.6</span> Robustness</a></li>
  </ul></li>
  <li><a href="#sec-conclusions" id="toc-sec-conclusions" class="nav-link" data-scroll-target="#sec-conclusions"><span class="header-section-number">6</span> Conclusions</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.1</span> Summary</a></li>
  <li><a href="#what-this-adds" id="toc-what-this-adds" class="nav-link" data-scroll-target="#what-this-adds"><span class="header-section-number">6.2</span> What this adds</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">6.3</span> Limitations</a></li>
  <li><a href="#ethical-considerations" id="toc-ethical-considerations" class="nav-link" data-scroll-target="#ethical-considerations"><span class="header-section-number">6.4</span> Ethical considerations</a></li>
  <li><a href="#future-directions" id="toc-future-directions" class="nav-link" data-scroll-target="#future-directions"><span class="header-section-number">6.5</span> Future directions</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6.6</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




  


<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Concern about automation is prevalent among American workers. According to Gallup, worries about technology rendering jobs obsolete surged significantly between 2021 and 2023 <span class="citation" data-cites="Gallup2023">(<a href="#ref-Gallup2023" role="doc-biblioref">Saad 2023</a>)</span>. Similarly, the Pew Research Center suggests that Americans expect automation to displace jobs held by others while leaving their own largely unaffected <span class="citation" data-cites="Pew2017">(<a href="#ref-Pew2017" role="doc-biblioref">Smith and Anderson 2017</a>)</span>. These surveys capture workers’ beliefs, but they don’t necessarily reflect the actual state of local labor markets. Empirical evidence is lacking to establish whether the concentration of automatable work in a county correlates with the economic conditions faced by its residents. This paper aims to investigate this association.</p>
<p><span class="citation" data-cites="Autor2003">Autor, Levy, and Murnane (<a href="#ref-Autor2003" role="doc-biblioref">2003</a>)</span> demonstrated that computers replace routine tasks and enhance non-routine tasks, enabling us to identify occupations susceptible to automation. <span class="citation" data-cites="AutorDorn2013">Autor and Dorn (<a href="#ref-AutorDorn2013" role="doc-biblioref">2013</a>)</span> applied this framework to local labor markets, revealing polarization in routine-intensive areas. In these areas, employment grew at both the high and low ends of the wage distribution, while middle-wage employment declined. <span class="citation" data-cites="AcemogluAutor2011">Acemoglu and Autor (<a href="#ref-AcemogluAutor2011" role="doc-biblioref">2011</a>)</span> generalized this approach into a model that explains how technology redistributes work across skill groups. This model remains the standard framework for empirical research on automation and labor markets.</p>
<p>None of this work asks what those wages buy where workers live. Outcomes are measured in unadjusted wages and employment shares rather than in local purchasing power. A high wage metropolitan area and a low wage rural county can therefore appear vastly different in dollar terms even when the goods those wages buy are comparable. The unit of analysis is also the commuting zone, which averages over the variation across the counties it contains. Neither feature is a flaw in the earlier studies, which were designed for different questions. Both limit what they can say about county level affordability.</p>
<p>This study asks how the automatability of local jobs relates to county affordability, and whether that relationship holds once poverty and unemployment are accounted for. We build a county by year panel covering 2008 to 2023, excluding 2020, from datasets published by federal agencies. Each county year is summarized by four task group values: routine cognitive, routine manual, non routine cognitive, and non routine manual. These follow the task framework of <span class="citation" data-cites="Autor2003">Autor, Levy, and Murnane (<a href="#ref-Autor2003" role="doc-biblioref">2003</a>)</span> and the occupation taxonomy of <span class="citation" data-cites="AutorDorn2013">Autor and Dorn (<a href="#ref-AutorDorn2013" role="doc-biblioref">2013</a>)</span>. The outcome is an affordability salary in dollars, defined as county median household income divided by the local price level from the BEA Regional Price Parities.</p>
<p>We first estimate a panel regression with year indicators and county clustered standard errors, which gives an interpretable estimate of the association. We then check that specification with residual plots, QQ plots, and variance inflation factors. Finally we fit random forest and neural network models to capture structure the linear model leaves behind. Model complexity increases only where diagnostics indicate the simpler specification is insufficient.</p>
<!--
TODO intro
- unify citation keys with references.bib and the data section.
-->
</section>
<section id="sec-background" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Background and Related Work</h1>
</section>
<section id="sec-data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data</h1>
<section id="data-collection" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-collection"><span class="header-section-number">3.1</span> Data collection</h2>
<p>Data for this analysis come from five datasets published by three U.S. federal agencies. Each was retrieved through an agency API or bulk file download and loaded into a PostgreSQL database. <a href="#tbl-sources" class="quarto-xref">Table&nbsp;1</a> reports each source, record counts, and the variables it supplies.</p>
<div id="tbl-sources" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Federal data sources and variables supplied
</figcaption>
<div aria-describedby="tbl-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Records retrieved</th>
<th>Variables supplied</th>
<th>Warehouse table</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Census SAIPE</td>
<td>50,283</td>
<td>median household income, poverty rate</td>
<td><code>county_baseline</code></td>
</tr>
<tr class="even">
<td>BEA Regional Price Parities</td>
<td>884</td>
<td>county price level relative to the national average</td>
<td><code>cbsa_rpp</code></td>
</tr>
<tr class="odd">
<td>Census CBSA delineation</td>
<td>387</td>
<td>county to metropolitan area crosswalk</td>
<td><code>cbsa</code></td>
</tr>
<tr class="even">
<td>ACS 1 year estimates</td>
<td>15,690</td>
<td>population, occupational employment by category</td>
<td><code>county_baseline</code>, <code>county_task_exposure</code></td>
</tr>
<tr class="odd">
<td>BLS LAUS</td>
<td>88,004</td>
<td>unemployment rate</td>
<td><code>county_baseline</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The five sources arrive at two levels of observation: county by year, and metropolitan area. The pipeline transforms each to a common county by year grain, and county FIPS code and year together serve as the join key across the warehouse. Regional Price Parities require one extra step. BEA publishes them at the metropolitan area level, so counties are linked to their metropolitan area through the Census CBSA delineation file before joining.</p>
<p>The study period spans 2008 to 2023, excluding 2020. ACS suspended its 1 year estimates that year following COVID related disruptions to data collection. Because those estimates supply the occupational employment counts underlying the task group values, the task groups cannot be constructed for 2020. The 3,156 counties in the Census county reference file observed over fifteen years yield 47,340 potential county year observations.</p>
</section>
<section id="measuring-task-structure" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="measuring-task-structure"><span class="header-section-number">3.2</span> Measuring task structure</h2>
<p>Following the task framework introduced in <a href="#sec-background" class="quarto-xref">Section&nbsp;2</a>, each of the broad occupational categories published in ACS 1 year estimates is assigned to one of four task groups: routine cognitive, routine manual, non routine cognitive, and non routine manual. The Census categories carry no such labels, so the assignment follows the classification logic of <span class="citation" data-cites="AutorDorn2013">Autor and Dorn (<a href="#ref-AutorDorn2013" role="doc-biblioref">2013</a>)</span>: clerical and sales work as routine cognitive, production and construction work as routine manual, managerial, professional and technical work as non routine cognitive, and service work as non routine manual. For each county and year, the task group totals are the employment sums across the categories assigned to each group, shown in <a href="#eq-weighted" class="quarto-xref">Equation&nbsp;1</a>.</p>
<p><span id="eq-weighted"><span class="math display">\[
T_{g,c,t} = \sum_{o \in g} E_{o,c,t}
\tag{1}\]</span></span></p>
<p>Here <span class="math inline">\(E_{o,c,t}\)</span> is employment in occupational category <span class="math inline">\(o\)</span> in county <span class="math inline">\(c\)</span> during year <span class="math inline">\(t\)</span>, and the sum runs over the categories assigned to group <span class="math inline">\(g\)</span>. The four totals are then divided by their sum, as in <a href="#eq-group" class="quarto-xref">Equation&nbsp;2</a>, so that each county year is described by four values on a zero to one scale that sum to one.</p>
<p><span id="eq-group"><span class="math display">\[
G_{g,c,t} = \frac{T_{g,c,t}}{\sum_{g'} T_{g',c,t}}
\tag{2}\]</span></span></p>
<p>Normalizing by the four group total converts employment counts into a composition, so counties of very different sizes are described on a common scale and the quantity of interest is the relative mix of work rather than its volume. The implications for estimation are reported in <a href="#sec-analysis" class="quarto-xref">Section&nbsp;4</a>.</p>
<p>Retaining four separate groups, rather than collapsing them into a single routine intensity index, preserves a distinction that a composite measure erases. Under one index, a county shifting away from clerical work and a county shifting away from assembly work look identical.</p>
</section>
<section id="measuring-affordability" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="measuring-affordability"><span class="header-section-number">3.3</span> Measuring affordability</h2>
<p>The outcome variable is affordability salary, defined in <a href="#eq-afford" class="quarto-xref">Equation&nbsp;3</a> as county median household income, from the Census SAIPE program, divided by the local Regional Price Parity. BEA publishes parities as an index with the national average set to 100, so dividing by 100 converts the index into a price multiplier.</p>
<p><span id="eq-afford"><span class="math display">\[
A_{c,t} = \frac{\text{Median household income}_{c,t}}{\text{RPP}_{c,t} / 100}
\tag{3}\]</span></span></p>
<p>A county with a median household income of $60,000 and a price parity of 120 has an affordability salary of $50,000, meaning local income buys what $50,000 would buy at national average prices. Stated this way, income is comparable across counties, since a given figure purchases roughly the same bundle wherever it appears.</p>
<p>The adjustment is spatial rather than temporal. Regional Price Parities correct for price differences across places but not across years, so affordability salary is not deflated to a constant base year. National price movement over the study period is absorbed by the year indicators in the regression rather than by the variable itself.</p>
<p>Counties outside any metropolitan area have no published parity of their own and take their state parity instead. Within the analytical panel, 45.5 percent of county year rows use a metropolitan parity and 54.5 percent use the state fallback. This is a substantive limitation, since a single state level price index is applied to counties whose actual price levels differ, and a majority of panel rows carry it. The counties involved are above the 65,000 population threshold but predominantly outside metropolitan statistical areas, where BEA publishes no local parity.</p>
</section>
<section id="control-variables" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="control-variables"><span class="header-section-number">3.4</span> Control variables</h2>
<p>Three baseline county conditions enter the models as controls. Unemployment rate comes from BLS LAUS and poverty rate from the Census SAIPE program, both measured in percentage points. Total population comes from ACS 1 year estimates and enters the models in logs. Unemployment and poverty capture labor market slack and material hardship that would otherwise be attributed to task structure. Population accounts for scale differences across counties, which range from the ACS publication threshold of 65,000 to the roughly 10.2 million residents of Los Angeles County.</p>
</section>
<section id="storage-and-organization" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="storage-and-organization"><span class="header-section-number">3.5</span> Storage and organization</h2>
<p>Data are stored in PostgreSQL across two databases that serve different purposes.</p>
<p>The first is a data lake of roughly 41 tables holding raw retrievals and intermediate results, deliberately left unnormalized. Its purpose is traceability. Any figure in this report can be traced back to the records it came from, and any processing step can be rerun without returning to an agency API, including retrievals for analysis branches later scoped out.</p>
<p>The second is the analytical warehouse of eleven tables, whose analytical core is in third normal form. All cleaning occurs upstream, so the warehouse is effectively read only from the perspective of the analysis. <a href="#fig-erd" class="quarto-xref">Figure&nbsp;1</a> shows the seven tables the analysis reads; a population staging table, a compatibility view, and an employment composition table retained from an earlier analysis branch are omitted.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-erd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-erd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-erd">erDiagram
    state {
        varchar state_code PK
        varchar state_name
    }
    county {
        bigint county_fips PK
        varchar county_name
        varchar state_code FK
    }
    cbsa {
        varchar cbsa_code PK
        varchar cbsa_name
    }
    county_cbsa_code {
        bigint county_fips PK,FK
        varchar cbsa_code PK,FK
    }
    cbsa_rpp {
        varchar cbsa_code PK,FK
        int year PK
        numeric rpp_value
    }
    county_baseline {
        bigint county_fips PK,FK
        int year PK
        numeric population
        numeric median_household_income
        numeric poverty_rate
        numeric unemployment_rate
    }
    county_task_exposure {
        bigint county_fips PK,FK
        int year PK
        numeric routine_cognitive
        numeric routine_manual
        numeric non_routine_cognitive
        numeric non_routine_manual
        numeric routine_cognitive_share "generated"
        numeric routine_manual_share "generated"
        numeric non_routine_cognitive_share "generated"
        numeric non_routine_manual_share "generated"
    }
    county_affordability {
        bigint county_fips PK,FK
        int year PK
        numeric affordability_salary
    }
    state ||--o{ county : contains
    county ||--o{ county_baseline : ""
    county ||--o{ county_task_exposure : ""
    county ||--o{ county_affordability : ""
    county ||--o{ county_cbsa_code : ""
    cbsa ||--o{ county_cbsa_code : ""
    cbsa ||--o{ cbsa_rpp : ""
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-erd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Warehouse schema in third normal form
</figcaption>
</figure>
</div>
</div>
</div>
<p>The schema centers on a <code>county</code> table keyed by FIPS code, with <code>state</code> as a reference table. Three fact tables join to <code>county</code> on FIPS code and year. <code>county_baseline</code> holds population, median household income, poverty rate and unemployment rate, <code>county_task_exposure</code> holds the four task group totals from <a href="#eq-weighted" class="quarto-xref">Equation&nbsp;1</a>, and <code>county_affordability</code> holds the outcome variable. The normalized values from <a href="#eq-group" class="quarto-xref">Equation&nbsp;2</a> are not computed in analysis code but stored as generated columns, which the database derives from the four totals on every write. The equation is enforced in the schema itself, so no analysis can read a stale or inconsistently normalized value.</p>
<p>Price parities require a separate path. Metropolitan membership is kept out of the <code>county</code> table and in the <code>county_cbsa_code</code> junction table, so counties outside any metropolitan area carry no null CBSA fields, and the crosswalk stands alone as its own fact. From there <code>cbsa</code> connects to <code>cbsa_rpp</code>. Storing parities at the CBSA level reflects the level at which BEA measures them and avoids repeating a single value across every county in a metropolitan area.</p>
</section>
<section id="the-analytical-dataset" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="the-analytical-dataset"><span class="header-section-number">3.6</span> The analytical dataset</h2>
<p>The 47,340 potential county year observations described above are the set of records the county table supports, not the set the models estimate on. Two filters reduce it.</p>
<p>Task group coverage is the binding constraint. The occupational employment counts that build the four task groups come from ACS 1 year estimates, which the Census Bureau publishes only for areas with populations above 65,000. Counties below that threshold have no occupational estimates in any year, so no task groups can be constructed for them. This removes 2,308 of the 3,156 counties outright and leaves 12,087 county year observations across 848 counties.</p>
<p>Requiring non missing controls removes a further 104 observations. Every one of the 104 is missing an unemployment rate, giving BLS LAUS a coverage rate of 99.1 percent across the retained counties. Population, median household income and poverty rate are complete. The estimation sample is therefore 11,983 county year observations, and all models reported in <a href="#sec-analysis" class="quarto-xref">Section&nbsp;4</a> and <a href="#sec-results" class="quarto-xref">Section&nbsp;5</a> fit on these same rows.</p>
<p>The population threshold shapes what the results can describe. The 848 retained counties hold the large majority of the United States population but a minority of its counties, and they are more metropolitan, more populous and more economically diverse than those dropped. Rural counties are underrepresented as a direct consequence. Findings should be read as applying to counties above 65,000 residents rather than to counties in general. <a href="#sec-conclusions" class="quarto-xref">Section&nbsp;6</a> returns to this limitation and to one approach for addressing it in future work.</p>
<!--
TODO data
- spot check the RPP split join before trusting 45.5/54.5: Multnomah (41051) should
  classify msa for all fifteen years
- recompute panel population share with SAIPE denominator on thomas; the 97.3/96.4
  result used county_baseline population, which is ACS sourced and null for sub 65k
  counties, inflating the share
- confirm which script writes county_employment_composition (suspected: ACS category
  counts, not PUMS)
-->
</section>
</section>
<section id="sec-analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Analysis</h1>
<section id="panel-regression" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="panel-regression"><span class="header-section-number">4.1</span> Panel regression</h2>
<p>The four task group values described in <a href="#eq-group" class="quarto-xref">Equation&nbsp;2</a> sum to one, so all four cannot enter a regression together. One serves as the reference category, and we use non routine cognitive. Each remaining coefficient represents the change in affordability salary associated with a shift out of non routine cognitive work and into that group, holding the controls fixed. Each coefficient is a comparison against the reference category. The group values are measured on a zero to one scale. Per percentage point figures reported later therefore divide the estimated coefficients by 100.</p>
<p>Normalizing the four totals by their sum, as <a href="#sec-data" class="quarto-xref">Section&nbsp;3</a> describes, also resolves a collinearity issue. Left unresolved, that issue would render these coefficients unusable. The unnormalized totals in <a href="#eq-weighted" class="quarto-xref">Equation&nbsp;1</a> exhibit variance inflation factors ranging from 13 to 27. All four are employment counts, so they scale together with county size. Dividing by the four group sum removes this common scale and reduces the variance inflation factors to approximately 1.</p>
<p>Year indicators capture conditions common to all counties within a year. These include the 2008 recession, the recovery through the 2010s, and the price movement that affordability salary does not itself account for. Standard errors are clustered by county, because repeated observations of the same county across fifteen years are not independent draws.</p>
</section>
<section id="validation-before-modeling" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="validation-before-modeling"><span class="header-section-number">4.2</span> Validation before modeling</h2>
<p>Before making any estimations, we ensure that the data support the chosen methods. We examine the distributions of the four task groups and the affordability salary to identify any skewness or outliers. Additionally, we verify that the county-year coverage is consistent across the retained panel. Furthermore, we check for any overlap between task groups to ensure that no two groups effectively carry the same information. Figure <a href="#fig-dists" class="quarto-xref">Figure&nbsp;2</a> provides visual representations of the distributions.</p>
<div id="cell-fig-dists" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-dists" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dists-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-dists-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;2: Distributions across the 12,087 county year panel. Affordability salary is right skewed with a long upper tail; the four task groups each show real cross county spread, with non routine cognitive the largest category."><img src="capstone_files/figure-html/fig-dists-output-2.png" width="636" height="305" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dists-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distributions across the 12,087 county year panel. Affordability salary is right skewed with a long upper tail; the four task groups each show real cross county spread, with non routine cognitive the largest category.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Affordability salaries are right-skewed, with a skewness of 1.17. The center of the distribution is located near $57,000, and a long tail of high-paying counties extends above it. This skewness is why the diagnostics below focus on the extremes of the distribution.</p>
</section>
<section id="specification-diagnostics" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="specification-diagnostics"><span class="header-section-number">4.3</span> Specification diagnostics</h2>
<p>A linear model assumes a constant rate of association across the data range and symmetrical, evenly distributed errors around the fit. We verify these assumptions using three diagnostics: residuals plotted against fitted values, a QQ plot of the residuals, and variance inflation factors. <a href="#fig-resid-analysis" class="quarto-xref">Figure&nbsp;3</a> illustrates the first two diagnostics, pinpointing the failure directly. The smoothed residual line deviates from zero, indicating a non-linear relationship. The vertical spread of residuals increases with fitted values. The model underestimates both the least and most affordable counties while fitting the middle well. Additionally, the QQ plot deviates from normality in the upper tail, suggesting a residual skew of 1.02.</p>
<div id="cell-fig-resid-analysis" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-resid-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resid-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-resid-analysis-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;3: Level model diagnostics. Left: residuals against fitted values with lowess smoother; the curve away from zero at both ends shows the model underpredicting the least and most affordable counties. Right: QQ plot of residuals; the bend above the line in the upper tail reflects the residual skew of 1.02."><img src="capstone_files/figure-html/fig-resid-analysis-output-1.png" width="826" height="346" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resid-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Level model diagnostics. Left: residuals against fitted values with lowess smoother; the curve away from zero at both ends shows the model underpredicting the least and most affordable counties. Right: QQ plot of residuals; the bend above the line in the upper tail reflects the residual skew of 1.02.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The level model still provides the interpretable estimates we report. Additionally, its own diagnostics demonstrate that the data possess a structure that a straight line in dollars cannot adequately represent. Binned means plots in <a href="#sec-results" class="quarto-xref">Section&nbsp;5</a> illustrate the underprediction in dollar terms, with approximately $8,000 to $9,000 of underprediction at each tail.</p>
</section>
<section id="log-respecification" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="log-respecification"><span class="header-section-number">4.4</span> Log respecification</h2>
<p>Underprediction at both extremes is a hallmark of a multiplicative process that is fitted on an additive scale. The factors influencing affordability operate proportionally, resulting in a more significant impact on a high-affordability county compared to a low-affordability one when a similar change occurs in an input variable. By converting the proportional effects into the additive form assumed by linear models, we refit the same specification on log affordability salary. Consequently, the diagnostics respond accordingly, as demonstrated by <a href="#fig-log-diag" class="quarto-xref">Figure&nbsp;4</a>. The residual skew decreases from 1.02 to 0.09, and the spread becomes relatively constant across the fitted range. The QQ plot also straightens through most of its range. The log linear fit serves as the baseline for evaluating the flexible models presented in the subsequent section.</p>
<div id="cell-fig-log-diag" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-log-diag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-log-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-log-diag-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;4: Log model diagnostics, same layout as the level model. The smoother lies close to zero, the spread is near constant, and the QQ plot tracks the diagonal through most of its range, showing the transformation resolves most of the level model’s failure."><img src="capstone_files/figure-html/fig-log-diag-output-1.png" width="826" height="346" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-log-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Log model diagnostics, same layout as the level model. The smoother lies close to zero, the spread is near constant, and the QQ plot tracks the diagonal through most of its range, showing the transformation resolves most of the level model’s failure.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The smoothed residual line doesn’t lie perfectly flat even after the transformation. The remaining deviations are structured in a way that a single global transformation cannot absorb, most likely due to interactions among the inputs. These deviations motivate the increase in model complexity.</p>
</section>
<section id="variance-decomposition" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="variance-decomposition"><span class="header-section-number">4.5</span> Variance decomposition</h2>
<p>Affordability, salary, and task groups vary both across counties and within a county over time. These variations have different implications. The two manual groups show almost complete variation between counties, with only 10-25% variation within a county on the corrected window. This makes the associated affordability differences more durable rather than temporary. Routine cognitive is the only group with genuine within-county movement, with nearly half of its variation on the corrected window.</p>
<p>The Census occupation coding change between 2009 and 2010, as described in <a href="#sec-data" class="quarto-xref">Section&nbsp;3</a>, inflates apparent within-county variation for the routine cognitive group. This is due to the way the source data were coded, not a property of the counties. Therefore, we repeat the main estimates on a panel restricted to 2010 onward and additionally on pre-pandemic (2010-2019) and post-pandemic (2021-2023) windows. Coefficient stability across these windows is reported in <a href="#sec-results" class="quarto-xref">Section&nbsp;5</a>, along with the between- versus within-county exhibits that support the claim of persistence.</p>
</section>
<section id="predictive-modeling" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="predictive-modeling"><span class="header-section-number">4.6</span> Predictive Modeling</h2>
<p>Beyond the inferential panel regression above, we evaluate three predictive approaches of increasing complexity: linear regression, Random Forest, and a small neural net. We check whether a flexible model captures meaningfully more signal than the linear specification. We reuse the county-year panel already assembled above, extended with state identifiers for the fixed effects comparison below.</p>
<section id="feature-set-and-reference-categories" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="feature-set-and-reference-categories"><span class="header-section-number">4.6.1</span> Feature set and reference categories</h3>
<p>Task shares are computed directly by the database as each category’s count divided by the four-category sum, so they already satisfy the constraint used in the panel regression above and require no additional normalization here. As before, one category must be dropped to avoid a deterministic column, and we retain <code>non_routine_cognitive_share</code> as the omitted reference for consistency with the panel regression.</p>
</section>
<section id="year-and-state-dummies" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="year-and-state-dummies"><span class="header-section-number">4.6.2</span> Year and state dummies</h3>
<p>Running year as a factor, not as numeric, gives each year its own independent coefficient, with no assumption about ordering or spacing between them.</p>
<p>Leaving one state as a reference state as well, which will be the median affordability state, whatever that may be in our data.</p>
<div id="2eac1072" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>States pooled into 'OTHER' (fewer than 5 counties): ['02', '10', '15', '31', '32', '38', '44', '46', '50', '56']
state_code_grouped
04       49162.399048
35       51120.150650
54       51612.794808
12       53792.854948
45       54053.901136
22       54540.841406
23       54883.638111
05       55211.965697
37       55284.510559
01       55354.050163
41       55387.832098
28       56112.461608
42       57701.695436
16       57767.458000
26       58288.849932
36       58523.412069
40       58552.186364
53       58731.325139
30       59131.600588
39       59250.894861
48       59699.104475
13       60044.603800
18       60127.991175
47       60180.907811
21       60525.209278
06       61605.522315
29       61665.309602
17       61803.834076
20       62548.987203
19       65244.072027
25       65694.014278
OTHER    65850.986514
55       65923.985812
33       66527.155934
08       69039.754624
49       69260.277813
34       71775.309619
51       72636.249933
24       75561.805000
27       76705.249375
Name: affordability_salary, dtype: float64

State/group closest to median affordability: 48
Year dummy columns: ['year_2009', 'year_2010', 'year_2011', 'year_2012', 'year_2013', 'year_2014', 'year_2015', 'year_2016', 'year_2017', 'year_2018', 'year_2019', 'year_2021', 'year_2022', 'year_2023']
Number of state dummy columns: 39</code></pre>
</div>
</div>
<p>Here we identify every state with fewer than 5 distinct counties in our data and relabel them as “OTHER.” They can’t reliably support their own independent coefficient otherwise.</p>
<p>Texas was selected as the reference state because its mean affordability sits closest to the panel median. It’s not a cost-of-living outlier in either direction, and it has enormous within-state diversity: major metros like Austin/Dallas/Houston alongside a huge number of rural counties. So, “different from Texas” is a fairly intuitive baseline for other states to be read against.</p>
<div id="cell-fig-state-afford" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-state-afford" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-state-afford-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-state-afford-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;5: Mean affordability salary by state, sorted ascending, with the panel median marked. Texas sits near the middle of the distribution, supporting its use as the reference state."><img src="capstone_files/figure-html/fig-state-afford-output-1.png" width="1155" height="458" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-state-afford-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Mean affordability salary by state, sorted ascending, with the panel median marked. Texas sits near the middle of the distribution, supporting its use as the reference state.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure <a href="#fig-state-afford" class="quarto-xref">Figure&nbsp;5</a> shows that Texas lies near the middle of the states in terms of affordability and is usable as a reference point.</p>
</section>
<section id="collinearity-check" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3" class="anchored" data-anchor-id="collinearity-check"><span class="header-section-number">4.6.3</span> Collinearity check</h3>
<p>Our four main features — <code>routine_cognitive_share</code>, <code>routine_manual_share</code>, <code>non_routine_cognitive_share</code>, <code>non_routine_manual_share</code> — are shares of a whole, thus we need to remove one in order to maintain independence (as the fourth is deterministic once you know the values of the other three). If we didn’t remove one, then one feature for certain would be a VIF offender.</p>
<p>The remaining three coefficients become interpretable as: the effect of shifting share toward this category, away from the omitted one.</p>
<div id="a13dad67" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>Exposure scores entering the model: ['routine_cognitive_share', 'routine_manual_share', 'non_routine_manual_share']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="11">
<div id="tbl-vif-ml" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="11">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-vif-ml-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Variance inflation factors for year and state dummies after removing the reference exposure category. All values fall below 5, indicating no remaining collinearity concern.
</figcaption>
<div aria-describedby="tbl-vif-ml-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="79">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">feature</th>
<th data-quarto-table-cell-role="th">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>year_2010</td>
<td>3.670674</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>year_2011</td>
<td>3.370305</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>year_2012</td>
<td>3.284874</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>year_2013</td>
<td>3.166672</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>year_2014</td>
<td>3.023630</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">12</td>
<td>year_2015</td>
<td>2.963071</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13</td>
<td>year_2016</td>
<td>2.904967</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">14</td>
<td>year_2017</td>
<td>2.851808</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">15</td>
<td>year_2018</td>
<td>2.580857</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">18</td>
<td>year_2022</td>
<td>2.531588</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-vif-ml" class="quarto-xref">Table&nbsp;2</a> lists the highest variance inflation factors after removal of <code>non_routine_cognitive_share</code>; no offender columns remain, as all features have VIF &lt; 5.</p>
</section>
<section id="traintest-split-grouped-by-county" class="level3" data-number="4.6.4">
<h3 data-number="4.6.4" class="anchored" data-anchor-id="traintest-split-grouped-by-county"><span class="header-section-number">4.6.4</span> Train/test split (grouped by county)</h3>
<p>Not forecasting, so a time-ordered split isn’t required for its usual reason. But we do want a grouped split because a county’s economic profile likely barely moves year to year, so its 2018 and 2019 rows are near-duplicates. Obviously, this is a problem, as if two sequential rows end up in opposite splits, the model can just memorize rather than learn relationships. So, we will group by <code>county_fips</code> when splitting to force every test-set prediction to come from a county the model has never seen a single row of. This ensures a test of whether the pattern is relationship driven rather than memorized.</p>
</section>
<section id="linear-regression-baseline-vs.-full-model" class="level3" data-number="4.6.5">
<h3 data-number="4.6.5" class="anchored" data-anchor-id="linear-regression-baseline-vs.-full-model"><span class="header-section-number">4.6.5</span> Linear regression: baseline vs.&nbsp;full model</h3>
<p>We report two versions of each linear model throughout this section: a <strong>baseline</strong> (exposure shares + poverty + unemployment only) and a <strong>full</strong> model (baseline + year and state controls). The baseline establishes what the relationship looks like without accounting for time/geography; the full model is what we carry forward as our primary result, as it’s the more rigorous version. Including both lets us demonstrate exactly what changes when time/geography are accounted for, and why.</p>
<section id="baseline-ols-no-yearstate" class="level4" data-number="4.6.5.1">
<h4 data-number="4.6.5.1" class="anchored" data-anchor-id="baseline-ols-no-yearstate"><span class="header-section-number">4.6.5.1</span> Baseline OLS (no year/state)</h4>
<div id="dcb09840" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>                             OLS Regression Results                             
================================================================================
Dep. Variable:     affordability_salary   R-squared:                       0.766
Model:                              OLS   Adj. R-squared:                  0.766
Method:                   Least Squares   F-statistic:                     6249.
Date:                  Mon, 03 Aug 2026   Prob (F-statistic):               0.00
Time:                          19:06:07   Log-Likelihood:                -99712.
No. Observations:                  9565   AIC:                         1.994e+05
Df Residuals:                      9559   BIC:                         1.995e+05
Df Model:                             5                                         
Covariance Type:              nonrobust                                         
============================================================================================
                               coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                     1.507e+05    835.105    180.507      0.000    1.49e+05    1.52e+05
routine_cognitive_share  -8.108e+04   2222.226    -36.488      0.000   -8.54e+04   -7.67e+04
routine_manual_share     -7.149e+04   1524.066    -46.907      0.000   -7.45e+04   -6.85e+04
non_routine_manual_share -1.305e+05   2451.216    -53.259      0.000   -1.35e+05   -1.26e+05
poverty_rate             -1376.4988     19.783    -69.582      0.000   -1415.277   -1337.721
unemployment_rate        -1207.1783     35.209    -34.286      0.000   -1276.196   -1138.161
==============================================================================
Omnibus:                     1808.774   Durbin-Watson:                   0.672
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5229.433
Skew:                           0.995   Prob(JB):                         0.00
Kurtosis:                       6.027   Cond. No.                         537.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>(Note that features are on wildly different scales.) R² = 0.766 is respectable. Every coefficient is negative and highly significant, which makes sense given that non-routine cognitive was our reference, and shifting county task mix toward any of the other categories is associated with lower affordability (though non-routine manual is the steepest).</p>
<p>NOTE: If we were doing predictions, the target skewness might be an issue and a log transform would be worth considering — tabled for now since we’re not forecasting.</p>
</section>
<section id="full-ols-with-yearstate-controls" class="level4" data-number="4.6.5.2">
<h4 data-number="4.6.5.2" class="anchored" data-anchor-id="full-ols-with-yearstate-controls"><span class="header-section-number">4.6.5.2</span> Full OLS (with year/state controls)</h4>
<div id="dfd06d32" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>routine_cognitive_share    -87421.198221
routine_manual_share       -81143.308583
non_routine_manual_share   -91904.212242
poverty_rate                -1728.819845
unemployment_rate             449.763793
dtype: float64
R-squared: 0.870637303564147</code></pre>
</div>
</div>
<p>With the addition of time and geography, the R² increased from 0.766 to 0.871 in the same model, implying that these variables explain real variance. Notably, the <code>unemployment_rate</code> coefficient flips sign, meaning that the baseline coefficient likely absorbed some of the geography and time confounding. This makes sense as unemployment-heavy places/times also tend to be low-affordability places/times. The full model’s coefficient reflects the within-state-year relationship instead. Also notable, the exposure mix coefficients maintained their direction and relative ordering through the addition of the new features.</p>
<p>Figure <a href="#fig-ols-diag" class="quarto-xref">Figure&nbsp;6</a> shows both diagnostics side by side.</p>
<div id="cell-fig-ols-diag" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div id="fig-ols-diag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ols-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-ols-diag-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;6: Full raw-target OLS diagnostics. Left: residuals against fitted values; the U-shaped pattern shows the model underpredicting at both extremes. Right: QQ plot of residuals, deviating from normality in the upper tail."><img src="capstone_files/figure-html/fig-ols-diag-output-1.png" width="804" height="346" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ols-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Full raw-target OLS diagnostics. Left: residuals against fitted values; the U-shaped pattern shows the model underpredicting at both extremes. Right: QQ plot of residuals, deviating from normality in the upper tail.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There is a clear U-shaped pattern to the residual plot, indicating that the residuals are not uniformly distributed, thus the OLS is not a reliable model for our data with the target as is.</p>
</section>
<section id="full-ols-with-yearstate-controls-and-log-target" class="level4" data-number="4.6.5.3">
<h4 data-number="4.6.5.3" class="anchored" data-anchor-id="full-ols-with-yearstate-controls-and-log-target"><span class="header-section-number">4.6.5.3</span> Full OLS (with year/state controls) and log target</h4>
<p>The binned affordability salary vs.&nbsp;affordability salary graphs showed an approximate exponential pattern, so we will investigate whether logging the target will make a linear model more appropriate.</p>
<div id="f1ce85c0" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>Any zero/negative affordability values? 0
Skew, original: 1.2324330032097133
Skew, logged:   0.458530959523057
                             OLS Regression Results                             
================================================================================
Dep. Variable:     affordability_salary   R-squared:                       0.913
Model:                              OLS   Adj. R-squared:                  0.912
Method:                   Least Squares   F-statistic:                     1718.
Date:                  Mon, 03 Aug 2026   Prob (F-statistic):               0.00
Time:                          19:06:08   Log-Likelihood:                 10999.
No. Observations:                  9565   AIC:                        -2.188e+04
Df Residuals:                      9506   BIC:                        -2.146e+04
Df Model:                            58                                         
Covariance Type:              nonrobust                                         
============================================================================================
                               coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       12.0395      0.010   1192.954      0.000      12.020      12.059
routine_cognitive_share     -1.0795      0.034    -31.520      0.000      -1.147      -1.012
routine_manual_share        -1.0892      0.017    -65.839      0.000      -1.122      -1.057
non_routine_manual_share    -1.2127      0.027    -45.269      0.000      -1.265      -1.160
poverty_rate                -0.0291      0.000   -132.649      0.000      -0.030      -0.029
unemployment_rate            0.0008      0.001      1.315      0.189      -0.000       0.002
year_2009                   -0.0121      0.005     -2.481      0.013      -0.022      -0.003
year_2010                    0.0367      0.006      6.053      0.000       0.025       0.049
year_2011                    0.0587      0.006     10.082      0.000       0.047       0.070
year_2012                    0.0808      0.006     14.185      0.000       0.070       0.092
year_2013                    0.0986      0.006     17.632      0.000       0.088       0.110
year_2014                    0.1119      0.005     20.483      0.000       0.101       0.123
year_2015                    0.1221      0.005     22.627      0.000       0.112       0.133
year_2016                    0.1314      0.005     24.519      0.000       0.121       0.142
year_2017                    0.1483      0.005     28.076      0.000       0.138       0.159
year_2018                    0.1708      0.005     33.885      0.000       0.161       0.181
year_2019                    0.1962      0.005     39.767      0.000       0.187       0.206
year_2021                    0.2320      0.005     47.543      0.000       0.222       0.242
year_2022                    0.2984      0.005     60.072      0.000       0.289       0.308
year_2023                    0.3233      0.005     66.363      0.000       0.314       0.333
state_01                    -0.0100      0.006     -1.720      0.086      -0.021       0.001
state_04                    -0.0424      0.009     -4.744      0.000      -0.060      -0.025
state_05                    -0.0378      0.007     -5.401      0.000      -0.052      -0.024
state_06                    -0.0066      0.005     -1.252      0.211      -0.017       0.004
state_08                    -0.0685      0.007     -9.437      0.000      -0.083      -0.054
state_12                    -0.1287      0.005    -26.686      0.000      -0.138      -0.119
state_13                     0.0065      0.005      1.390      0.165      -0.003       0.016
state_16                    -0.0715      0.009     -8.235      0.000      -0.088      -0.054
state_17                    -0.0388      0.006     -6.211      0.000      -0.051      -0.027
state_18                    -0.0376      0.005     -7.075      0.000      -0.048      -0.027
state_19                    -0.0171      0.008     -2.086      0.037      -0.033      -0.001
state_20                    -0.0419      0.009     -4.782      0.000      -0.059      -0.025
state_21                    -0.0118      0.006     -1.868      0.062      -0.024       0.001
state_22                     0.0186      0.006      2.912      0.004       0.006       0.031
state_23                    -0.1901      0.012    -16.006      0.000      -0.213      -0.167
state_24                    -0.0332      0.007     -5.103      0.000      -0.046      -0.020
state_25                    -0.1004      0.007    -14.046      0.000      -0.114      -0.086
state_26                    -0.0488      0.005     -8.920      0.000      -0.060      -0.038
state_27                    -0.0035      0.007     -0.501      0.617      -0.017       0.010
state_28                     0.0060      0.007      0.805      0.421      -0.009       0.021
state_29                    -0.0494      0.006     -8.577      0.000      -0.061      -0.038
state_30                    -0.1131      0.010    -11.639      0.000      -0.132      -0.094
state_33                    -0.1528      0.009    -16.217      0.000      -0.171      -0.134
state_34                    -0.0543      0.006     -8.637      0.000      -0.067      -0.042
state_35                    -0.0016      0.010     -0.168      0.867      -0.021       0.017
state_36                    -0.1117      0.005    -22.893      0.000      -0.121      -0.102
state_37                    -0.0613      0.005    -13.070      0.000      -0.071      -0.052
state_39                    -0.0408      0.005     -8.530      0.000      -0.050      -0.031
state_40                    -0.0128      0.007     -1.892      0.059      -0.026       0.000
state_41                    -0.0950      0.006    -14.849      0.000      -0.107      -0.082
state_42                    -0.1086      0.005    -22.748      0.000      -0.118      -0.099
state_45                    -0.0487      0.006     -8.234      0.000      -0.060      -0.037
state_47                    -0.0375      0.006     -6.518      0.000      -0.049      -0.026
state_49                    -0.0180      0.010     -1.796      0.073      -0.038       0.002
state_51                    -0.0480      0.005     -9.412      0.000      -0.058      -0.038
state_53                    -0.0697      0.007    -10.148      0.000      -0.083      -0.056
state_54                    -0.0796      0.009     -9.107      0.000      -0.097      -0.062
state_55                    -0.0430      0.006     -7.553      0.000      -0.054      -0.032
state_OTHER                 -0.0343      0.005     -6.334      0.000      -0.045      -0.024
==============================================================================
Omnibus:                      183.701   Durbin-Watson:                   0.677
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              316.447
Skew:                           0.160   Prob(JB):                     1.92e-69
Kurtosis:                       3.832   Cond. No.                         747.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Figure <a href="#fig-ols-log-diag" class="quarto-xref">Figure&nbsp;7</a> shows the same pair of diagnostics for the log-target specification.</p>
<div id="cell-fig-ols-log-diag" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div id="fig-ols-log-diag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ols-log-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-ols-log-diag-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;7: Log-target OLS diagnostics, same layout as the raw-target model. The residual spread is roughly constant across fitted values and the QQ plot tracks the diagonal much more closely."><img src="capstone_files/figure-html/fig-ols-log-diag-output-1.png" width="826" height="346" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ols-log-diag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Log-target OLS diagnostics, same layout as the raw-target model. The residual spread is roughly constant across fitted values and the QQ plot tracks the diagonal much more closely.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The residual plot looks uniformly distributed and the QQ plot follows a straight line pattern, so with a logged target we can use a linear model.</p>
<div id="bd892302" class="cell" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>R-squared (log target, in-sample): 0.9128887327038346
Test R2 (log space): 0.8894251280521438
Test R2 (back-transformed to $): 0.8957661959388022
Test MAE (back-transformed to $): 3635.5329144913035</code></pre>
</div>
</div>
<p>With a logged target, the model achieves an in-sample R² of 0.913 and a held-out test R² (transformed back into dollars) of 0.896. Both are notably higher than the raw-target model’s 0.871, and with valid residual diagnostics.</p>
</section>
<section id="baseline-vs.-full-comparison-table" class="level4" data-number="4.6.5.4">
<h4 data-number="4.6.5.4" class="anchored" data-anchor-id="baseline-vs.-full-comparison-table"><span class="header-section-number">4.6.5.4</span> Baseline vs.&nbsp;full comparison table</h4>
<div class="cell" data-execution_count="20">
<div id="tbl-ols-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="20">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ols-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Coefficients across the baseline, full raw-target, and full log-target OLS specifications, with log-target coefficients also converted to percent change per one-point shift.
</figcaption>
<div aria-describedby="tbl-ols-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="88">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">baseline</th>
<th data-quarto-table-cell-role="th">with_controls (raw $)</th>
<th data-quarto-table-cell-role="th">with_controls (log target)</th>
<th data-quarto-table-cell-role="th">log_target (% change per 1pp)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">const</td>
<td>150742.645766</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">non_routine_manual_share</td>
<td>-130549.425753</td>
<td>-91904.212242</td>
<td>-1.212747</td>
<td>-1.205423</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">poverty_rate</td>
<td>-1376.498808</td>
<td>-1728.819845</td>
<td>-0.029121</td>
<td>-2.870075</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">routine_cognitive_share</td>
<td>-81084.753276</td>
<td>-87421.198221</td>
<td>-1.079544</td>
<td>-1.073738</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">routine_manual_share</td>
<td>-71490.091428</td>
<td>-81143.308583</td>
<td>-1.089197</td>
<td>-1.083287</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unemployment_rate</td>
<td>-1207.178313</td>
<td>449.763793</td>
<td>0.000803</td>
<td>0.080349</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>As <a href="#tbl-ols-comparison" class="quarto-xref">Table&nbsp;3</a> shows, <code>unemployment_rate</code>’s sign flip is confirmed across all three fitted forms. Exposure coefficients shrink in magnitude from baseline to raw-controls while <code>poverty_rate</code> grows (−1,376.50 → −1,728.82).</p>
<p>Each additional percentage point of poverty rate is associated with roughly a 2.9% decrease in affordability, holding time, geography, and task-mix fixed. This is a considerably larger proportional effect than any single task-mix category.</p>
<div class="cell" data-execution_count="21">
<div id="tbl-ols-r2-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="21">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ols-r2-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: R-squared by specification stage: baseline, full raw-target (diagnostics failed), and full log-target.
</figcaption>
<div aria-describedby="tbl-ols-r2-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="89">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">model</th>
<th data-quarto-table-cell-role="th">r2_or_note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Baseline OLS</td>
<td>0.765744</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Full OLS (raw $, diagnostics failed)</td>
<td>0.870637</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Full OLS (log target)</td>
<td>0.912889</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-ols-r2-summary" class="quarto-xref">Table&nbsp;4</a> shows R² climbing through each stage of this analysis. First, adding year and state controls to the baseline model (0.766 → 0.871) confirms that time and geography explain real, previously unmodeled variance. Logging the target (0.871 → 0.913 in-sample, 0.896 held-out) accounts for even more variance once the residual violations from the raw-target model are resolved. This is the model used for inference going forward, since the raw-target model’s coefficient significance cannot be trusted given its failed residual diagnostics above.</p>
</section>
</section>
<section id="random-forest" class="level3" data-number="4.6.6">
<h3 data-number="4.6.6" class="anchored" data-anchor-id="random-forest"><span class="header-section-number">4.6.6</span> Random Forest</h3>
<p>For a Random Forest (RF), we performed a grid search using <code>n_estimators</code>, <code>max_depth</code>, <code>min_samples_leaf</code>, and <code>max_features</code> over the grid shown below. Given a high number of estimators to reduce variance, and <code>max_depth</code>/<code>min_samples_leaf</code> to add potential regularization.</p>
<p>An R² of 0.876 is higher than the raw-target OLS model (0.871), suggesting at least some non-linear relationship in the data at this stage. However, as shown above, this comparison changes once the target is log-transformed, which will be addressed in the comparison below.</p>
<p>A train/test gap of 0.989 vs.&nbsp;0.876 tells us that the ceiling on this feature set is being constrained by something other than hyperparameters. We are already fitting training data about as well as a tree ensemble can, we just aren’t getting better generalization.</p>
<div id="cell-fig-rf-resid" class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<div id="fig-rf-resid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rf-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-rf-resid-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;8: Random Forest residuals against predicted values on the held-out test set. No systematic curve or trend is visible across the range of predictions."><img src="capstone_files/figure-html/fig-rf-resid-output-1.png" width="672" height="442" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rf-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Random Forest residuals against predicted values on the held-out test set. No systematic curve or trend is visible across the range of predictions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Unlike the raw-target OLS residuals, Figure <a href="#fig-rf-resid" class="quarto-xref">Figure&nbsp;8</a> shows Random Forest’s residuals with no systematic curve or trend across the range of predicted values.</p>
<section id="ablation-test" class="level5" data-number="4.6.6.0.1">
<h5 data-number="4.6.6.0.1" class="anchored" data-anchor-id="ablation-test"><span class="header-section-number">4.6.6.0.1</span> Ablation test</h5>
<div id="2a7aac79" class="cell" data-execution_count="26">
<div class="cell-output cell-output-stdout">
<pre><code>R2 without exposure scores: 0.8339992605886773</code></pre>
</div>
</div>
<p>Without accounting for automatability at all, the same Random Forest achieves an R² of 0.834.</p>
</section>
<section id="reverse-ablation-test" class="level5" data-number="4.6.6.0.2">
<h5 data-number="4.6.6.0.2" class="anchored" data-anchor-id="reverse-ablation-test"><span class="header-section-number">4.6.6.0.2</span> Reverse ablation test</h5>
<div id="8b8b0035" class="cell" data-execution_count="27">
<div class="cell-output cell-output-stdout">
<pre><code>R2 without poverty/unemployment: 0.6983607085809014</code></pre>
</div>
</div>
<p>Using only the automatability scores (excluding poverty and unemployment), the model reaches an R² of 0.698 — meaningful on its own, but well short of the full model.</p>
</section>
<section id="testing-rf-with-logged-target" class="level5" data-number="4.6.6.0.3">
<h5 data-number="4.6.6.0.3" class="anchored" data-anchor-id="testing-rf-with-logged-target"><span class="header-section-number">4.6.6.0.3</span> Testing RF with logged target</h5>
<p>Logging the target could be good for RF too, so we run that as well.</p>
<div id="2c5b9cb7" class="cell" data-execution_count="28">
<div class="cell-output cell-output-stdout">
<pre><code>Test R2 (log space): 0.8781823460727236
Test R2 (back-transformed to $): 0.8768487377842192
Test MAE (back-transformed to $): 3916.409028061873</code></pre>
</div>
</div>
<p>An R² of 0.877 after back-transforming — a negligible change from the untransformed-target model (0.876). Since the log-target model is already established as the reference model for the linear regression above, we adopt log-target RF here as well for consistency in the final comparison, even though the choice of target makes little practical difference for Random Forest specifically.</p>
</section>
<section id="grouped-permutation-the-actual-combination-question" class="level4" data-number="4.6.6.1">
<h4 data-number="4.6.6.1" class="anchored" data-anchor-id="grouped-permutation-the-actual-combination-question"><span class="header-section-number">4.6.6.1</span> Grouped permutation — the actual “combination” question</h4>
<p>To see what the four exposure scores do together, rather than one at a time diluting each other, we permute all four jointly and compare the drop in R² to permuting them individually.</p>
<div id="badef59d" class="cell" data-execution_count="29">
<div class="cell-output cell-output-stdout">
<pre><code>Baseline R2: 0.8762409382895193
Drop from permuting all exposure scores together: 0.1531310972084307
Drop from permuting routine_cognitive_share alone: 0.025615576618095576
Drop from permuting routine_manual_share alone: 0.03706460532391171
Drop from permuting non_routine_manual_share alone: 0.048090402537186584
Drop from permuting year (jointly): 0.12740689943244296
Drop from permuting state (jointly): 0.008320346919784616</code></pre>
</div>
</div>
<p>Year matters far more than state (0.127 vs.&nbsp;0.008): time, not geography, carries the bulk of the “when/where” signal once economic and exposure score variables are controlled for.</p>
<p>Exposure score gross importance (0.153) is considerably larger than its net/irreplaceable contribution of 0.042 from the ablation test in RF. This implies that it shares (mostly) real predictive overlap with poverty, unemployment, and time, but still adds something those don’t fully capture.</p>
<p>Among the three individual task shares, <code>non_routine_manual_share</code> shows the largest individual sensitivity (though none of the three should be read as independently additive given they are parts of a whole).</p>
</section>
</section>
<section id="simple-neural-net" class="level3" data-number="4.6.7">
<h3 data-number="4.6.7" class="anchored" data-anchor-id="simple-neural-net"><span class="header-section-number">4.6.7</span> Simple neural net</h3>
<p>We will build a simple neural net. As it is likely already a bit overkill, we will keep it shallow and the layers narrow. We are still doing a regression and our target is continuous, so we will have a single linear output unit.</p>
<div id="e876baff" class="cell" data-execution_count="30">
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bold"> 1/76</span> <span class="ansi-white-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">4s</span> 63ms/step

<span class="ansi-bold">42/76</span> <span class="ansi-green-fg">━━━━━━━━━━━</span><span class="ansi-white-fg">━━━━━━━━━</span> <span class="ansi-bold">0s</span> 1ms/step 

<span class="ansi-bold">76/76</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">0s</span> 2ms/step

<span class="ansi-bold">76/76</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">0s</span> 2ms/step

Test R2:  0.8432590928458205

Test MAE: 4607.2755303970225

Stopped at epoch: 18

Best val_loss achieved: 0.24777477979660034
</pre>
</div>
</div>
</div>
<div id="cell-fig-nn-curve-initial" class="cell" data-execution_count="31">
<div class="cell-output cell-output-display">
<div id="fig-nn-curve-initial" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-curve-initial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-nn-curve-initial-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;9: Training and validation loss for the initial, unregularized neural net. Training loss plateaus below 0.1 while validation loss falls to roughly 0.2 before rising to about 0.5, indicating overfitting."><img src="capstone_files/figure-html/fig-nn-curve-initial-output-1.png" width="609" height="453" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-curve-initial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Training and validation loss for the initial, unregularized neural net. Training loss plateaus below 0.1 while validation loss falls to roughly 0.2 before rising to about 0.5, indicating overfitting.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure <a href="#fig-nn-curve-initial" class="quarto-xref">Figure&nbsp;9</a> shows training loss decreasing steadily and plateauing below 0.1, while validation loss initially decreases to approximately 0.2 before rising to roughly 0.5, a clear indication of overfitting. We address this with L2 weight regularization, increased dropout, and a shorter early-stopping patience.</p>
<div id="f2e01cf6" class="cell" data-execution_count="32">
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre>Stopped at epoch: 48

Best val_loss achieved: 0.17765924334526062


<span class="ansi-bold"> 1/76</span> <span class="ansi-white-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">3s</span> 47ms/step

<span class="ansi-bold">62/76</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━</span><span class="ansi-white-fg">━━━━</span> <span class="ansi-bold">0s</span> 822us/step

<span class="ansi-bold">76/76</span> <span class="ansi-green-fg">━━━━━━━━━━━━━━━━━━━━</span> <span class="ansi-bold">0s</span> 1ms/step  

Test R2: 
 0.8726706021904944

Test MAE: 4024.4236937810174
</pre>
</div>
</div>
</div>
<div id="cell-fig-nn-curve-regularized" class="cell" data-execution_count="33">
<div class="cell-output cell-output-display">
<div id="fig-nn-curve-regularized" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-curve-regularized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-nn-curve-regularized-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;10: Training and validation loss after adding L2 regularization, increased dropout, and shorter early-stopping patience. The train/validation gap narrows relative to the initial model."><img src="capstone_files/figure-html/fig-nn-curve-regularized-output-1.png" width="592" height="453" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-curve-regularized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Training and validation loss after adding L2 regularization, increased dropout, and shorter early-stopping patience. The train/validation gap narrows relative to the initial model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure <a href="#fig-nn-curve-regularized" class="quarto-xref">Figure&nbsp;10</a> shows the training curve after these changes. Additional tuning could likely narrow the remaining gap between training and validation loss further. However, the current results are sufficient to draw the conclusion that the neural network does not outperform Random Forest or the log-target linear model, both of which are substantially cheaper to fit and tune. Given this project’s emphasis on explaining the relationship between job automatability and affordability rather than maximizing predictive accuracy, we do not pursue further tuning of the neural network and proceed with the linear and Random Forest models as our primary results.</p>
</section>
<section id="cross-validation" class="level3" data-number="4.6.8">
<h3 data-number="4.6.8" class="anchored" data-anchor-id="cross-validation"><span class="header-section-number">4.6.8</span> Cross validation</h3>
<p>After exploring and comparing the explained variance of the three different models, we cross-validate to give the models more generalizability.</p>
<div class="cell" data-execution_count="34">
<div class="cell-output cell-output-stdout">
<pre><code>Fold 0: OLS(log)=0.911 RF=0.916
Fold 1: OLS(log)=0.894 RF=0.888
Fold 2: OLS(log)=0.892 RF=0.901
Fold 3: OLS(log)=0.914 RF=0.899
Fold 4: OLS(log)=0.893 RF=0.902</code></pre>
</div>
<div id="tbl-cv-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="34">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Mean and standard deviation of held-out R-squared across 5-fold grouped cross-validation for log-target OLS and Random Forest.
</figcaption>
<div aria-describedby="tbl-cv-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="101">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean_r2</th>
<th data-quarto-table-cell-role="th">std_r2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">OLS (log target)</td>
<td>0.900724</td>
<td>0.009480</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Random Forest</td>
<td>0.901373</td>
<td>0.008994</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>As <a href="#tbl-cv-summary" class="quarto-xref">Table&nbsp;5</a> shows, across 5-fold cross-validation, OLS (log target) and Random Forest are statistically indistinguishable (mean R² of 0.901 and 0.901, respectively), with Random Forest showing marginally lower variance across folds (std 0.0090 vs.&nbsp;0.0095). This confirms the single-split result below is not an artifact of one particular split, and both models generalize consistently and comparably across held-out counties.</p>
<p>Note that the neural net was not included, as cross-validating would be very expensive, and as noted above it will not be carried forward for that reason.</p>
<p>Model comparison across test R² and MAE, along with the full ablation-test takeaways, appears in <a href="#sec-results" class="quarto-xref">Section&nbsp;5</a>.</p>
</section>
</section>
<section id="wrap-up-summary" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="wrap-up-summary"><span class="header-section-number">4.7</span> Wrap-up summary</h2>
<p>Three specifications answer three different questions. The panel regression, with county-clustered standard errors, is the model we use for inference. It tells us that routine-intensive work is associated with lower affordability salary even after controlling for poverty, unemployment, time, and geography. Its log respecification resolves the residual violations that make the raw target version untrustworthy for that purpose.</p>
<p>The predictive models answer the different question of how much of affordability salary can be explained at all, and by what. Random Forest and the log-target linear model perform comparably on held-out data, which tells us the relationship’s curvature adds little once poverty, unemployment, time, and geography are already in the model. The neural net does not improve on either, and its added complexity is not justified by this feature set.</p>
<p>Across both approaches, task-mix shares carry real, independent explanatory power, but poverty rate remains the dominant single factor throughout. This ordering, not any one model’s fit statistic, is the finding this analysis is built to support, and it is what <a href="#sec-results" class="quarto-xref">Section&nbsp;5</a> carries forward.</p>
<!--
TODO analysis
- confirm RESET test statistic and p-value against current model run (referenced
  in @sec-results but not computed here)
- restricted 2010-onward panel estimates, mentioned in Variance decomposition but
  not yet run
Section rules from the in class template:
1. Cover only the models most important to understanding the results.
2. Depth is a function of audience.
3. If a method's output does not appear in the results, it does not belong here.
4. Equations must be explained and referenced before they appear, and units stated.
5. Do not narrate dead ends or the chronology of what we tried.
-->
</section>
</section>
<section id="sec-results" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Results</h1>
<section id="where-affordability-is-strained" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="where-affordability-is-strained"><span class="header-section-number">5.1</span> Where affordability is strained</h2>
<!-- FIGURE: fig-affordmap. EXISTS, poster Figure 4. Affordability salary by county,
     averaged across the study period. Choropleth, darker means income stretches further.
     Poster version was built on the old full frame, needs rebuilding on the 848 county
     panel. Purpose is orientation: the outcome has geographic structure before any
     modeling. -->
<!-- FIGURE: fig-gapmap. EXISTS, poster Figure 1. Median household income minus
     affordability salary, red where income overstates purchasing power and blue where it
     understates. Justifies the price adjustment in one image. Poster caption says 3,114
     counties, so it predates the current panel and needs rebuilding. Decide whether both
     maps are needed or whether this one alone does the work. -->
</section>
<section id="task-groups-and-affordability" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="task-groups-and-affordability"><span class="header-section-number">5.2</span> Task groups and affordability</h2>
<p>The panel regression returns a negative association between routine intensive work and affordability salary that holds after controls. A one percentage point shift toward Nonroutine Manual work is associated with roughly $846 (± $38) less in affordability salary, evaluated at the panel mean.</p>
<p><a href="#fig-coefplot" class="quarto-xref">Figure&nbsp;11</a> shows each task group’s coefficient with its confidence interval, non routine cognitive as the reference.</p>
<!-- FIGURE: fig-coefplot. NEW, poster has it as an In Progress placeholder only.
     Coefficient plot, task group on the y axis, association with affordability salary on
     the x axis, points with error bars, non routine cognitive as the reference. The
     figure that turns the whole project into one number, so it carries more weight than
     any other here. -->
<div id="cell-fig-coefplot" class="cell" data-execution_count="39">
<div class="cell-output cell-output-display">
<div id="fig-coefplot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coefplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-coefplot-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;11: Task group association with affordability salary (log target), non-routine cognitive as reference. Points show coefficients; bars show 95% confidence intervals from county-clustered standard errors."><img src="capstone_files/figure-html/fig-coefplot-output-1.png" width="703" height="346" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coefplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Task group association with affordability salary (log target), non-routine cognitive as reference. Points show coefficients; bars show 95% confidence intervals from county-clustered standard errors.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The associations survive the addition of poverty rate and the other baseline controls, so the task groups are not standing in for poverty. <a href="#fig-coefcompare" class="quarto-xref">Figure&nbsp;12</a> puts the coefficients before and after controls side by side.</p>
<!-- FIGURE: fig-coefcompare. NEW, poster has it as an In Progress placeholder only.
     Paired coefficient plot or forest plot, each task group before and after adding
     poverty and the baseline controls. Answers the objection that the task groups are
     poverty in disguise, which the importance chart invites. -->
<div id="cell-fig-coefcompare" class="cell" data-execution_count="40">
<div class="cell-output cell-output-display">
<div id="fig-coefcompare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coefcompare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-coefcompare-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;12: Task group coefficients before (baseline) and after (full model) adding poverty and demographic controls. Stable coefficients indicate task groups are not standing in for poverty."><img src="capstone_files/figure-html/fig-coefcompare-output-1.png" width="720" height="442" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coefcompare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Task group coefficients before (baseline) and after (full model) adding poverty and demographic controls. Stable coefficients indicate task groups are not standing in for poverty.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="nonlinearity" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="nonlinearity"><span class="header-section-number">5.3</span> Nonlinearity</h2>
<p>The RESET test rejects the linear specification [TK: statistic and p value], and <a href="#fig-binned" class="quarto-xref">Figure&nbsp;13</a> shows why. Binned means of affordability salary across the range of routine cognitive work rise and then fall rather than tracking a straight line.</p>
<!-- FIGURE: fig-binned. EXISTS, poster Figure 5. Binned means of affordability salary
     across the range of routine cognitive, actual and random forest predicted on the same
     axes. Should port over close to as is. The residual plot that pairs with it is
     claimed by _04 as well, resolve before building either. -->
<div id="cell-fig-binned" class="cell" data-execution_count="41">
<div class="cell-output cell-output-display">
<div id="fig-binned" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binned-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-binned-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;13: Binned means of affordability salary across routine cognitive employment share, actual vs.&nbsp;Random Forest predicted. The non-monotonic pattern is what a linear model cannot represent."><img src="capstone_files/figure-html/fig-binned-output-1.png" width="681" height="639" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binned-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Binned means of affordability salary across routine cognitive employment share, actual vs.&nbsp;Random Forest predicted. The non-monotonic pattern is what a linear model cannot represent.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-modelcomp" class="quarto-xref">Figure&nbsp;14</a> compares held out performance across specifications. The random forest reaches a test R² of 0.877 against 0.896 for the log-target linear model, and 0.873 for the neural network. The gap is evidence that the relationship has curvature the linear model cannot represent, which is the same conclusion the RESET test reaches by a different route.</p>
<!-- FIGURE: fig-modelcomp. EXISTS, poster Figure 3. Bar chart of held out test R squared
     for OLS, ridge, random forest, neural net, showing 0.610, 0.610, 0.840, 0.739.
     Poster draft 4 floats merging this with the binned means into one progression figure,
     which would make it NEW. Decide before building. -->
<div id="cell-fig-modelcomp" class="cell" data-execution_count="42">
<div class="cell-output cell-output-display">
<div id="fig-modelcomp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-modelcomp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-modelcomp-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;14: Held-out test R² across three model specifications. Random Forest and the log-target linear model perform comparably; both outperform the neural net."><img src="capstone_files/figure-html/fig-modelcomp-output-1.png" width="634" height="442" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-modelcomp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Held-out test R² across three model specifications. Random Forest and the log-target linear model perform comparably; both outperform the neural net.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-matters-most" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="what-matters-most"><span class="header-section-number">5.4</span> What matters most</h2>
<p>Poverty rate is the strongest single feature in the random forest, by a wide margin (<a href="#fig-importance" class="quarto-xref">Figure&nbsp;15</a>). Task groups follow, with non routine manual ranked highest among them. This ordering is consistent with the regression: poverty carries most of the explanatory weight, and the task groups add to it rather than substituting for it.</p>
<!-- FIGURE: fig-importance. EXISTS, poster Figure 6. Feature importance, horizontal
     bars, mean drop in test R squared when shuffled, ordered poverty rate, routine
     cognitive, non routine manual, unemployment, routine manual. Note the poster titles
     it "permutation importance", change to feature importance when porting. -->
<div id="fig-importance" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="43">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>

</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15
</figcaption>
</figure>
</div>
<p>As shown in <a href="#fig-importance" class="quarto-xref">Figure&nbsp;15</a>, permutation importance for <code>poverty_rate</code> at 0.625 is overwhelmingly the largest number here, which is consistent with every model’s findings so far. <code>non_routine_manual_share</code> is the highest of our task-mix categories, with <code>routine_manual_share</code> next, and <code>routine_cognitive_share</code> last.</p>
<!-- FIGURE: fig-pdp. NEW, poster has it as an In Progress placeholder only. Partial
     dependence for the task groups. Chris to supply. Also referenced from _04, pick one
     home. -->
<div id="cell-fig-pdp" class="cell" data-execution_count="44">
<div class="cell-output cell-output-display">
<div id="fig-pdp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-pdp-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;16: Partial dependence of predicted affordability salary (raw dollars) on each task group’s employment share, holding other features at their observed distribution."><img src="capstone_files/figure-html/fig-pdp-output-1.png" width="826" height="346" class="figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Partial dependence of predicted affordability salary (raw dollars) on each task group’s employment share, holding other features at their observed distribution.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="stability-over-time" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="stability-over-time"><span class="header-section-number">5.5</span> Stability over time</h2>
<p>A county’s task mix moves very little across the fifteen year panel [TK: quantify]. This matters for interpretation. Because the mix is close to a fixed characteristic of place, the affordability differences associated with it do not fade, and they are not something residents can be expected to move out from under.</p>
<!-- FIGURE: fig-stability. NEW, poster has it as an In Progress placeholder only.
     Stacked area chart, year on the x axis, share of total task weight on the y axis,
     four bands. Shows the mix holds steady across the panel. Carries the persistence
     claim the conclusions lean on, so it should not stay as a sentence. -->
</section>
<section id="robustness" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="robustness"><span class="header-section-number">5.6</span> Robustness</h2>
<p>Restricting the panel to 2010 onward, which removes the occupation coding change described in <a href="#sec-data" class="quarto-xref">Section&nbsp;3</a>, leaves the main associations intact [TK: report the restricted estimates].</p>
<!--
TODO results

What this section is for:

1. If it can be shown visually, show it. Prefer figures to tables and to in text
   description.
2. Every figure stands on its own. A reader who has not read the rest of the paper
   should get it from the figure and its caption alone.
3. One idea per figure. If two figures overlap, cut one or combine them into panels.
4. Storyboard. Arrange the figures in the order that tells the story, then write to
   them. Rearrange freely until the sequence holds together.
5. Open by hitting the highlights of the figures. Do not recapitulate them. The text is
   complementary to the figures, not a transcript of them.
6. Use the remaining text for what no figure carries.
7. Tables only if a figure cannot do it, and then keep them small.

Complete:

- the 1,041 figure, its sign, standard error, and which group carries the largest
  coefficient (now computed automatically from model_log as panel_effects/largest_group)
- test R squared for all three models (ridge dropped; OLS, Random Forest, and neural
  net R squared now pulled directly from the results dataframe rather than hardcoded)
- resolve the two figures claimed by both this section and _04: the residual plot stays
  in _04 only, feature importance stays here only as fig-importance
- captions are self contained, stating units and what the axes are, not just naming
  the figure

Still to do:

- remaining numbers in prose (RESET test statistic and p value) are still unconfirmed,
  check against the current model run
- quantify how little the task mix moves
- restricted 2010 onward estimates, and decide whether they live here or in _04
- ten figures are referenced. Five exist in some form on the poster (fig-affordmap,
  fig-gapmap, fig-binned, fig-modelcomp, fig-importance) and five are new
  (fig-coefplot, fig-coefcompare, fig-pdp, fig-stability, and the residual plot). Under
  rule 3 ten is too many. Storyboard and cut, most likely candidates are one of the two
  choropleths and merging the binned means with the model comparison
- the poster figures were built on the old full frame, all need rebuilding on the 848
  county panel before the numbers in the text can be trusted
-->
</section>
</section>
<section id="sec-conclusions" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusions</h1>
<section id="summary" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.1</span> Summary</h2>
<p>We asked whether counties with more automatable work are less affordable for the people who live in them. Building a county by year panel from eight federal sources, summarizing each county’s work by four task groups, and measuring affordability as median household income adjusted for local prices, we find that the answer is yes and that the relationship holds once poverty and unemployment are accounted for. Poverty is by a wide margin the strongest single correlate of county affordability. The task mix is a smaller but separate one.</p>
</section>
<section id="what-this-adds" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="what-this-adds"><span class="header-section-number">6.2</span> What this adds</h2>
<p>Two patterns are worth stating plainly before the broader claim. Poverty is the strongest single correlate of county affordability, but the task mix relates to affordability independently of it. And neither relationship is a straight line: routine cognitive work shows a rise then fall pattern, and poverty’s association is steepest at low levels and flattens at high ones.</p>
<p>The task framework has been applied to wages and to employment composition, mostly at the national or commuting zone level. Applying it to a cost adjusted outcome at the county level changes what the measure describes: not what work pays, but what that pay buys where it is earned. Two findings follow from that shift. The association is present after controlling for local economic distress, so it is not poverty in different clothing. And it is not linear, which the RESET test establishes and the flexible models exploit, so studies that assume a straight line relationship between task composition and local outcomes are leaving structure on the table.</p>
<p>The finding lands on people through place. Residents of routine work counties see their incomes buy systematically less, and because a county’s task mix barely moves across fifteen years, the difference is built into where they live rather than something individual effort resolves. Three groups can act on that. Economic development agencies deciding where workforce training goes, since the task mix separates structurally exposed counties from those in a temporary downturn. Policymakers and planners designing cost of living responses, since these gaps will not close on their own. And researchers extending the framework, since both the county level link and its nonlinear shape point past existing national wage studies.</p>
</section>
<section id="limitations" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="limitations"><span class="header-section-number">6.3</span> Limitations</h2>
<p>The results are associational. Counties are not assigned their mix of work, and nothing in this design isolates a causal channel, so we cannot say that automatable work makes a place less affordable, only that the two move together.</p>
<p>The four task groups are parts of a whole and sum to one, so one had to serve as a reference category. Every coefficient is read relative to non routine cognitive work rather than in isolation.</p>
<p>Coverage is the sharpest constraint. Task group values exist for 12,087 of the 47,340 county year combinations in the frame, and dropping the 104 rows missing an unemployment rate leaves 11,983 for estimation across 848 counties. The counties that fall out are small ones, below the population threshold at which the American Community Survey publishes one year occupational estimates, so the panel describes metropolitan and larger non metropolitan counties rather than the country.</p>
<p>Regional Price Parities are published for metropolitan areas, so counties outside one take their state value. Roughly 55 percent of county year rows use that fallback, which applies a single price index to counties whose actual price levels differ, and it falls disproportionately on rural places.</p>
<p>2020 is excluded because the American Community Survey did not release one year estimates for it. The 2009 to 2010 occupation coding change is a source artifact that inflates measured within county variance for routine cognitive work; restricting to 2010 onward leaves the conclusions unchanged.</p>
<p>The machine learning results rest on a single train and test split [TK: replace with cross validation if time allows].</p>
</section>
<section id="ethical-considerations" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="ethical-considerations"><span class="header-section-number">6.4</span> Ethical considerations</h2>
<p>All data are public county level aggregates with no individual records, so no person can be identified. Two harms are worth naming. Labeling counties as exposed or stuck could stigmatize them or steer investment away from the places that need it. And reading the association as causal could motivate policy that tries to reshape a county’s mix of work in the expectation that affordability follows, which this study does not support.</p>
</section>
<section id="future-directions" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="future-directions"><span class="header-section-number">6.5</span> Future directions</h2>
<p>Two extensions would address the limitations above directly.</p>
<p>The coverage gap could be narrowed with satellite imagery. <span class="citation" data-cites="Jean2016">Jean et al. (<a href="#ref-Jean2016" role="doc-biblioref">2016</a>)</span> estimate local economic conditions from daytime and nighttime imagery where survey data are thin, an approach that could recover the small counties this panel excludes and allow the affordability pattern to be retested on them.</p>
<p>Finer grained labor data would move the work closer to a causal claim. Splitting the task mix by worker education and status would separate the effect of workforce composition from the effect of the task mix itself, which the current design cannot disentangle.</p>
</section>
<section id="conclusion" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6.6</span> Conclusion</h2>
<p>[TK: the closing paragraph. Zelner’s fourth move, the one that ties it together. What does it all mean, why does it matter, what sticks with the reader. This is the place to be a little more opinionated. Draft line to work from: poverty remains the strongest correlate of county affordability, but the mix of work a county holds is a separate pressure on top of it, and poverty and unemployment statistics alone do not capture the full picture of affordability risk.]</p>
<!--
TODO conclusions

What this section is for:

1. Summarize. A reader who opened straight to this paragraph should learn what we did.
2. Sell the product. The affirmative case. Why the approach suited the question, which
   gap from the background it closes. No need to be negative about other work.
3. Limitations, then future directions. Limitations are stopping points that mark the
   boundary of the analysis, not an undermining of it. A well written limitations
   paragraph adds credibility. Future directions is where to plant a flag on what comes
   next.
4. Conclusion. Tie it together, say why it matters, be a little more opinionated.

IMPORTANT TO NOTE: do not claim more than the analysis supports, and do not narrate the
process or dead ends.

Structural questions still open:

- move 4 is missing, the section currently ends on future work. TK placeholder added
- ethics sits between limitations and future directions, which breaks Zelner's order.
  Either move it before limitations or into _01. The poster puts it in the intro panel
- "What this adds" now opens with the two discussion bullets and then makes the
  contribution argument, so it does two jobs. Consider splitting or trimming
- the first paragraph of "What this adds" repeats the poverty point from the summary

Content still to do:

- keep the limitations list in sync with whatever _05 ends up reporting
- the nonlinearity claim about poverty tapering at high levels comes from the poster
  partial dependence, confirm it holds in the current run before stating it
-->
</section>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-AcemogluAutor2011" class="csl-entry" role="listitem">
Acemoglu, Daron, and David Autor. 2011. <span>“Skills, Tasks and Technologies: Implications for Employment and Earnings.”</span> In <em>Handbook of Labor Economics</em>, edited by David Card and Orley Ashenfelter, 4:1043–1171. Elsevier. <a href="https://doi.org/10.1016/S0169-7218(11)02410-5">https://doi.org/10.1016/S0169-7218(11)02410-5</a>.
</div>
<div id="ref-AutorDorn2013" class="csl-entry" role="listitem">
Autor, David H., and David Dorn. 2013. <span>“The Growth of Low-Skill Service Jobs and the Polarization of the <span>US</span> Labor Market.”</span> <em>American Economic Review</em> 103 (5): 1553–97. <a href="https://doi.org/10.1257/aer.103.5.1553">https://doi.org/10.1257/aer.103.5.1553</a>.
</div>
<div id="ref-Autor2003" class="csl-entry" role="listitem">
Autor, David H., Frank Levy, and Richard J. Murnane. 2003. <span>“The Skill Content of Recent Technological Change: An Empirical Exploration.”</span> <em>The Quarterly Journal of Economics</em> 118 (4): 1279–1333. <a href="https://doi.org/10.1162/003355303322552801">https://doi.org/10.1162/003355303322552801</a>.
</div>
<div id="ref-Jean2016" class="csl-entry" role="listitem">
Jean, Neal, Marshall Burke, Michael Xie, W. Matthew Davis, David B. Lobell, and Stefano Ermon. 2016. <span>“Combining Satellite Imagery and Machine Learning to Predict Poverty.”</span> <em>Science</em> 353 (6301): 790–94. <a href="https://doi.org/10.1126/science.aaf7894">https://doi.org/10.1126/science.aaf7894</a>.
</div>
<div id="ref-Gallup2023" class="csl-entry" role="listitem">
Saad, Lydia. 2023. <span>“More <span>U.S.</span> Workers Fear Technology Making Their Jobs Obsolete.”</span> Gallup. <a href="https://news.gallup.com/poll/510551/workers-fear-technology-making-jobs-obsolete.aspx">https://news.gallup.com/poll/510551/workers-fear-technology-making-jobs-obsolete.aspx</a>.
</div>
<div id="ref-Pew2017" class="csl-entry" role="listitem">
Smith, Aaron, and Monica Anderson. 2017. <span>“Automation in Everyday Life.”</span> Pew Research Center. <a href="https://www.pewresearch.org/internet/2017/10/04/automation-in-everyday-life/">https://www.pewresearch.org/internet/2017/10/04/automation-in-everyday-life/</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>