{
  "hash": "7d4f4adc10fab5a0934c1a01e6bc4d52",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"How Job Automatability Relates to County Affordability\"\nsubtitle: Subtitle\nauthors:\n  - Chris Bell\n  - Julian Pacheco\nbibliography: references.bib\ntitle-block-banner: true\nformat:\n  html:\n    theme:\n      light: lightly\n      dark: darkly\n---\n\n# Introduction {#sec-intro}\n\nConcern about automation is prevalent among American workers. According to Gallup, worries about technology rendering jobs obsolete surged significantly between 2021 and 2023 [@Gallup2023]. Similarly, the Pew Research Center suggests that Americans expect automation to displace jobs held by others while leaving their own largely unaffected [@Pew2017]. These surveys capture workers’ beliefs, but they don’t necessarily reflect the actual state of local labor markets. Empirical evidence is lacking to establish whether the concentration of automatable work in a county correlates with the economic conditions faced by its residents. This paper aims to investigate this association.\n\n@Autor2003 demonstrated that computers replace routine tasks and enhance non-routine tasks, enabling us to identify occupations susceptible to automation. @AutorDorn2013 applied this framework to local labor markets, revealing polarization in routine-intensive areas. In these areas, employment grew at both the high and low ends of the wage distribution, while middle-wage employment declined. @AcemogluAutor2011 generalized this approach into a model that explains how technology redistributes work across skill groups. This model remains the standard framework for empirical research on automation and labor markets.\n\nNone of this work asks what those wages buy where workers live. Outcomes are measured in unadjusted wages and employment shares rather than in local purchasing power. A high wage metropolitan area and a low wage rural county can therefore appear vastly different in dollar terms even when the goods those wages buy are comparable. The unit of analysis is also the commuting zone, which averages over the variation across the counties it contains. Neither feature is a flaw in the earlier studies, which were designed for different questions. Both limit what they can say about county level affordability.\n\nThis study asks how the automatability of local jobs relates to county affordability, and whether that relationship holds once poverty and unemployment are accounted for. We build a county by year panel covering 2008 to 2023, excluding 2020, from datasets published by federal agencies. Each county year is summarized by four task group values: routine cognitive, routine manual, non routine cognitive, and non routine manual. These follow the task framework of @Autor2003 and the occupation taxonomy of @AutorDorn2013. The outcome is an affordability salary in dollars, defined as county median household income divided by the local price level from the BEA Regional Price Parities.\n\nWe first estimate a panel regression with year indicators and county clustered standard errors, which gives an interpretable estimate of the association. We then check that specification with residual plots, QQ plots, and variance inflation factors. Finally we fit random forest and neural network models to capture structure the linear model leaves behind. Model complexity increases only where diagnostics indicate the simpler specification is insufficient.\n\n<!--\nTODO intro\n- unify citation keys with references.bib and the data section.\n-->\n\n# Background and Related Work {#sec-background}\n\n# Data {#sec-data}\n\n## Data collection\n\nData for this analysis come from five datasets published by three U.S. federal agencies. Each was retrieved through an agency API or bulk file download and loaded into a PostgreSQL database. @tbl-sources reports each source, record counts, and the variables it supplies.\n\n| Source | Records retrieved | Variables supplied | Warehouse table |\n|---|---|---|---|\n| Census SAIPE | 50,283 | median household income, poverty rate | `county_baseline` |\n| BEA Regional Price Parities | 884 | county price level relative to the national average | `cbsa_rpp` |\n| Census CBSA delineation | 387 | county to metropolitan area crosswalk | `cbsa` |\n| ACS 1 year estimates | 15,690 | population, occupational employment by category | `county_baseline`, `county_task_exposure` |\n| BLS LAUS | 88,004 | unemployment rate | `county_baseline` |\n\n: Federal data sources and variables supplied {#tbl-sources}\n\nThe five sources arrive at two levels of observation: county by year, and metropolitan area. The pipeline transforms each to a common county by year grain, and county FIPS code and year together serve as the join key across the warehouse. Regional Price Parities require one extra step. BEA publishes them at the metropolitan area level, so counties are linked to their metropolitan area through the Census CBSA delineation file before joining.\n\nThe study period spans 2008 to 2023, excluding 2020. ACS suspended its 1 year estimates that year following COVID related disruptions to data collection. Because those estimates supply the occupational employment counts underlying the task group values, the task groups cannot be constructed for 2020. The 3,156 counties in the Census county reference file observed over fifteen years yield 47,340 potential county year observations.\n\n## Measuring task structure\n\nFollowing the task framework introduced in @sec-background, each of the broad occupational categories published in ACS 1 year estimates is assigned to one of four task groups: routine cognitive, routine manual, non routine cognitive, and non routine manual. The Census categories carry no such labels, so the assignment follows the classification logic of @AutorDorn2013: clerical and sales work as routine cognitive, production and construction work as routine manual, managerial, professional and technical work as non routine cognitive, and service work as non routine manual. For each county and year, the task group totals are the employment sums across the categories assigned to each group, shown in @eq-weighted.\n\n$$\nT_{g,c,t} = \\sum_{o \\in g} E_{o,c,t}\n$$ {#eq-weighted}\n\nHere $E_{o,c,t}$ is employment in occupational category $o$ in county $c$ during year $t$, and the sum runs over the categories assigned to group $g$. The four totals are then divided by their sum, as in @eq-group, so that each county year is described by four values on a zero to one scale that sum to one.\n\n$$\nG_{g,c,t} = \\frac{T_{g,c,t}}{\\sum_{g'} T_{g',c,t}}\n$$ {#eq-group}\n\nNormalizing by the four group total converts employment counts into a composition, so counties of very different sizes are described on a common scale and the quantity of interest is the relative mix of work rather than its volume. The implications for estimation are reported in @sec-analysis.\n\nRetaining four separate groups, rather than collapsing them into a single routine intensity index, preserves a distinction that a composite measure erases. Under one index, a county shifting away from clerical work and a county shifting away from assembly work look identical.\n\n## Measuring affordability\n\nThe outcome variable is affordability salary, defined in @eq-afford as county median household income, from the Census SAIPE program, divided by the local Regional Price Parity. BEA publishes parities as an index with the national average set to 100, so dividing by 100 converts the index into a price multiplier.\n\n$$\nA_{c,t} = \\frac{\\text{Median household income}_{c,t}}{\\text{RPP}_{c,t} / 100}\n$$ {#eq-afford}\n\nA county with a median household income of \\$60,000 and a price parity of 120 has an affordability salary of \\$50,000, meaning local income buys what \\$50,000 would buy at national average prices. Stated this way, income is comparable across counties, since a given figure purchases roughly the same bundle wherever it appears.\n\nThe adjustment is spatial rather than temporal. Regional Price Parities correct for price differences across places but not across years, so affordability salary is not deflated to a constant base year. National price movement over the study period is absorbed by the year indicators in the regression rather than by the variable itself.\n\nCounties outside any metropolitan area have no published parity of their own and take their state parity instead. Within the analytical panel, 45.5 percent of county year rows use a metropolitan parity and 54.5 percent use the state fallback. This is a substantive limitation, since a single state level price index is applied to counties whose actual price levels differ, and a majority of panel rows carry it. The counties involved are above the 65,000 population threshold but predominantly outside metropolitan statistical areas, where BEA publishes no local parity.\n\n## Control variables\n\nThree baseline county conditions enter the models as controls. Unemployment rate comes from BLS LAUS and poverty rate from the Census SAIPE program, both measured in percentage points. Total population comes from ACS 1 year estimates and enters the models in logs. Unemployment and poverty capture labor market slack and material hardship that would otherwise be attributed to task structure. Population accounts for scale differences across counties, which range from the ACS publication threshold of 65,000 to the roughly 10.2 million residents of Los Angeles County.\n\n## Storage and organization\n\nData are stored in PostgreSQL across two databases that serve different purposes.\n\nThe first is a data lake of roughly 41 tables holding raw retrievals and intermediate results, deliberately left unnormalized. Its purpose is traceability. Any figure in this report can be traced back to the records it came from, and any processing step can be rerun without returning to an agency API, including retrievals for analysis branches later scoped out.\n\nThe second is the analytical warehouse of eleven tables, whose analytical core is in third normal form. All cleaning occurs upstream, so the warehouse is effectively read only from the perspective of the analysis. @fig-erd shows the seven tables the analysis reads; a population staging table, a compatibility view, and an employment composition table retained from an earlier analysis branch are omitted.\n\n```{mermaid}\n%%| label: fig-erd\n%%| fig-cap: \"Warehouse schema in third normal form\"\nerDiagram\n    state {\n        varchar state_code PK\n        varchar state_name\n    }\n    county {\n        bigint county_fips PK\n        varchar county_name\n        varchar state_code FK\n    }\n    cbsa {\n        varchar cbsa_code PK\n        varchar cbsa_name\n    }\n    county_cbsa_code {\n        bigint county_fips PK,FK\n        varchar cbsa_code PK,FK\n    }\n    cbsa_rpp {\n        varchar cbsa_code PK,FK\n        int year PK\n        numeric rpp_value\n    }\n    county_baseline {\n        bigint county_fips PK,FK\n        int year PK\n        numeric population\n        numeric median_household_income\n        numeric poverty_rate\n        numeric unemployment_rate\n    }\n    county_task_exposure {\n        bigint county_fips PK,FK\n        int year PK\n        numeric routine_cognitive\n        numeric routine_manual\n        numeric non_routine_cognitive\n        numeric non_routine_manual\n        numeric routine_cognitive_share \"generated\"\n        numeric routine_manual_share \"generated\"\n        numeric non_routine_cognitive_share \"generated\"\n        numeric non_routine_manual_share \"generated\"\n    }\n    county_affordability {\n        bigint county_fips PK,FK\n        int year PK\n        numeric affordability_salary\n    }\n    state ||--o{ county : contains\n    county ||--o{ county_baseline : \"\"\n    county ||--o{ county_task_exposure : \"\"\n    county ||--o{ county_affordability : \"\"\n    county ||--o{ county_cbsa_code : \"\"\n    cbsa ||--o{ county_cbsa_code : \"\"\n    cbsa ||--o{ cbsa_rpp : \"\"\n```\n\nThe schema centers on a `county` table keyed by FIPS code, with `state` as a reference table. Three fact tables join to `county` on FIPS code and year. `county_baseline` holds population, median household income, poverty rate and unemployment rate, `county_task_exposure` holds the four task group totals from @eq-weighted, and `county_affordability` holds the outcome variable. The normalized values from @eq-group are not computed in analysis code but stored as generated columns, which the database derives from the four totals on every write. The equation is enforced in the schema itself, so no analysis can read a stale or inconsistently normalized value.\n\nPrice parities require a separate path. Metropolitan membership is kept out of the `county` table and in the `county_cbsa_code` junction table, so counties outside any metropolitan area carry no null CBSA fields, and the crosswalk stands alone as its own fact. From there `cbsa` connects to `cbsa_rpp`. Storing parities at the CBSA level reflects the level at which BEA measures them and avoids repeating a single value across every county in a metropolitan area.\n\n## The analytical dataset\n\nThe 47,340 potential county year observations described above are the set of records the county table supports, not the set the models estimate on. Two filters reduce it.\n\nTask group coverage is the binding constraint. The occupational employment counts that build the four task groups come from ACS 1 year estimates, which the Census Bureau publishes only for areas with populations above 65,000. Counties below that threshold have no occupational estimates in any year, so no task groups can be constructed for them. This removes 2,308 of the 3,156 counties outright and leaves 12,087 county year observations across 848 counties.\n\nRequiring non missing controls removes a further 104 observations. Every one of the 104 is missing an unemployment rate, giving BLS LAUS a coverage rate of 99.1 percent across the retained counties. Population, median household income and poverty rate are complete. The estimation sample is therefore 11,983 county year observations, and all models reported in @sec-analysis and @sec-results fit on these same rows.\n\nThe population threshold shapes what the results can describe. The 848 retained counties hold the large majority of the United States population but a minority of its counties, and they are more metropolitan, more populous and more economically diverse than those dropped. Rural counties are underrepresented as a direct consequence. Findings should be read as applying to counties above 65,000 residents rather than to counties in general. @sec-conclusions returns to this limitation and to one approach for addressing it in future work.\n\n<!--\nTODO data\n- spot check the RPP split join before trusting 45.5/54.5: Multnomah (41051) should\n  classify msa for all fifteen years\n- recompute panel population share with SAIPE denominator on thomas; the 97.3/96.4\n  result used county_baseline population, which is ACS sourced and null for sub 65k\n  counties, inflating the share\n- confirm which script writes county_employment_composition (suspected: ACS category\n  counts, not PUMS)\n-->\n\n# Analysis {#sec-analysis}\n\n::: {#7a3e2386 .cell .hidden execution_count=1}\n``` {.python .cell-code .hidden}\nimport os\nimport pandas as pd\nimport numpy as np\nimport statsmodels.api as sm\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\nfrom sqlalchemy import create_engine\nfrom dotenv import load_dotenv\n\nload_dotenv()\n\nengine=create_engine(os.environ[\"AUTORACK_URL\"])\ndf=pd.read_sql(\"\"\"\nselect ca.county_fips, ca.year, ca.affordability_salary,\n    cte.routine_cognitive_share, cte.routine_manual_share,\n    cte.non_routine_cognitive_share, cte.non_routine_manual_share,\n    cb.poverty_rate, cb.unemployment_rate, cb.population\nfrom county_affordability ca\njoin county_task_exposure cte on ca.county_fips=cte.county_fips and ca.year=cte.year\njoin county_baseline cb on ca.county_fips=cb.county_fips and ca.year=cb.year\n\"\"\", engine)\ndf[\"log_population\"]=np.log(df[\"population\"])\n```\n:::\n\n\n::: {#8a295f0a .cell .hidden execution_count=2}\n``` {.python .cell-code .hidden}\n# level model: OLS with year indicators, standard errors clustered by county\nreg_cols=[\"routine_cognitive_share\",\"routine_manual_share\",\"non_routine_manual_share\",\n          \"poverty_rate\",\"unemployment_rate\",\"log_population\"]\n\nreg=df.dropna(subset=reg_cols+[\"affordability_salary\"]).copy()\n\nX=pd.concat([reg[reg_cols],\n             pd.get_dummies(reg[\"year\"], prefix=\"year\", drop_first=True).astype(float)], axis=1)\nX=sm.add_constant(X)\n\nmodel=sm.OLS(reg[\"affordability_salary\"], X).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": reg[\"county_fips\"]})\n\nreg[\"fitted\"]=model.fittedvalues\nreg[\"resid\"]=model.resid\n\n# log respecification, same design matrix\nreg[\"actual_log\"]=np.log(reg[\"affordability_salary\"])\nmodel_log=sm.OLS(reg[\"actual_log\"], X).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": reg[\"county_fips\"]})\nreg[\"resid_log\"]=model_log.resid\n```\n:::\n\n\n:::{#d9070df0 .cell .markdown}\n## Panel regression\n\nThe four task group values described in @eq-group sum to one, so all four cannot enter a\nregression together. One serves as the reference category, and we use non routine\ncognitive. Each remaining coefficient represents the change in affordability salary\nassociated with a shift out of non routine cognitive work and into that group, holding\nthe controls fixed. Each coefficient is a comparison against the reference category. The\ngroup values are measured on a zero to one scale. Per percentage point figures reported\nlater therefore divide the estimated coefficients by 100.\n\nNormalizing the four totals by their sum, as @sec-data describes, also resolves a\ncollinearity issue. Left unresolved, that issue would render these coefficients unusable.\nThe unnormalized totals in @eq-weighted exhibit variance inflation factors ranging from\n13 to 27. All four are employment counts, so they scale together with county size.\nDividing by the four group sum removes this common scale and reduces the variance\ninflation factors to approximately 1.\n\nYear indicators capture conditions common to all counties within a year. These include\nthe 2008 recession, the recovery through the 2010s, and the price movement that\naffordability salary does not itself account for. Standard errors are clustered by\ncounty, because repeated observations of the same county across fifteen years are not\nindependent draws.\n\n## Validation before modeling\n\nBefore making any estimations, we ensure that the data support the chosen methods. We examine the distributions of the four task groups and the affordability salary to identify any skewness or outliers. Additionally, we verify that the county-year coverage is consistent across the retained panel. Furthermore, we check for any overlap between task groups to ensure that no two groups effectively carry the same information. Figure @fig-dists provides visual representations of the distributions.\n:::\n\n::: {#cell-fig-dists .cell execution_count=3}\n``` {.python .cell-code .hidden}\nshare_cols=[\"routine_cognitive_share\",\"routine_manual_share\",\n            \"non_routine_cognitive_share\",\"non_routine_manual_share\"]\n\ntitles=[\"Routine Cognitive\",\"Routine Manual\",\"Non Routine Cognitive\",\"Non Routine Manual\"]\n\nlayout=[[\"afford\",\"afford\"],\n        [\"rc\",\"rm\"],\n        [\"nrc\",\"nrm\"]]\n\nfig, axes=plt.subplot_mosaic(layout, figsize=(6.5, 3))\n\nsns.histplot(data=df, x=\"affordability_salary\", bins=50, ax=axes[\"afford\"])\naxes[\"afford\"].set_title(\"Affordability Salary ($)\")\naxes[\"afford\"].set_xlabel(\"\")\n\nfor key, col, title in zip([\"rc\",\"rm\",\"nrc\",\"nrm\"], share_cols, titles):\n    sns.histplot(data=df, x=col, bins=50, color=\"#009E73\", ax=axes[key])\n    axes[key].set_title(title)\n    axes[key].set_xlabel(\"\")\n    axes[key].set_ylabel(\"\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n```\nC:\\Users\\bellc\\AppData\\Local\\Temp\\ipykernel_19200\\4222824601.py:22: UserWarning:\n\nTight layout not applied. tight_layout cannot make Axes height small enough to accommodate all Axes decorations.\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Distributions across the 12,087 county year panel. Affordability salary is right skewed with a long upper tail; the four task groups each show real cross county spread, with non routine cognitive the largest category.](capstone_files/figure-html/fig-dists-output-2.png){#fig-dists width=636 height=305}\n:::\n:::\n\n\n:::{#abb8f3a7 .cell .markdown}\nAffordability salaries are right-skewed, with a skewness of 1.17. The center of the distribution is located near \\$57,000, and a long tail of high-paying counties extends above it. This skewness is why the diagnostics below focus on the extremes of the distribution.\n\n## Specification diagnostics\n\nA linear model assumes a constant rate of association across the data range and symmetrical, evenly distributed errors around the fit. We verify these assumptions using three diagnostics: residuals plotted against fitted values, a QQ plot of the residuals, and variance inflation factors. @fig-resid-analysis illustrates the first two diagnostics, pinpointing the failure directly. The smoothed residual line deviates from zero, indicating a non-linear relationship. The vertical spread of residuals increases with fitted values. The model underestimates both the least and most affordable counties while fitting the middle well. Additionally, the QQ plot deviates from normality in the upper tail, suggesting a residual skew of 1.02.\n:::\n\n::: {#cell-fig-resid-analysis .cell execution_count=4}\n``` {.python .cell-code .hidden}\nfig, axes=plt.subplots(1, 2, figsize=(9,4))\n\nsns.scatterplot(data=reg, x=\"fitted\", y=\"resid\", alpha=0.1, s=5, color=\"grey\", ax=axes[0])\nsns.regplot(data=reg, x=\"fitted\", y=\"resid\", scatter=False, lowess=True,\n            line_kws={\"color\":\"#D55E00\"}, ax=axes[0])\naxes[0].axhline(0, color=\"black\", linewidth=1)\naxes[0].set_title(\"Residuals Against Fitted Values\")\naxes[0].set_xlabel(\"Affordability Salary ($)\")\naxes[0].set_ylabel(\"Residual ($)\")\n\nstats.probplot(reg[\"resid\"], dist=\"norm\", plot=axes[1])\naxes[1].set_title(\"QQ Plot\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Level model diagnostics. Left: residuals against fitted values with lowess smoother; the curve away from zero at both ends shows the model underpredicting the least and most affordable counties. Right: QQ plot of residuals; the bend above the line in the upper tail reflects the residual skew of 1.02.](capstone_files/figure-html/fig-resid-analysis-output-1.png){#fig-resid-analysis width=826 height=346}\n:::\n:::\n\n\n:::{#08548b02 .cell .markdown}\nThe level model still provides the interpretable estimates we report. Additionally, its own diagnostics demonstrate that the data possess a structure that a straight line in dollars cannot adequately represent. Binned means plots in @sec-results illustrate the underprediction in dollar terms, with approximately \\$8,000 to \\$9,000 of underprediction at each tail.\n\n## Log respecification\n\nUnderprediction at both extremes is a hallmark of a multiplicative process that is fitted on an additive scale. The factors influencing affordability operate proportionally, resulting in a more significant impact on a high-affordability county compared to a low-affordability one when a similar change occurs in an input variable. By converting the proportional effects into the additive form assumed by linear models, we refit the same specification on log affordability salary. Consequently, the diagnostics respond accordingly, as demonstrated by @fig-log-diag. The residual skew decreases from 1.02 to 0.09, and the spread becomes relatively constant across the fitted range. The QQ plot also straightens through most of its range. The log linear fit serves as the baseline for evaluating the flexible models presented in the subsequent section.\n:::\n\n::: {#cell-fig-log-diag .cell execution_count=5}\n``` {.python .cell-code .hidden}\nreg[\"fitted_log\"]=model_log.fittedvalues\n\nfig, axes=plt.subplots(1, 2, figsize=(9,4))\n\nsns.scatterplot(data=reg, x=\"fitted_log\", y=\"resid_log\", alpha=0.1, s=5, color=\"grey\", ax=axes[0])\nsns.regplot(data=reg, x=\"fitted_log\", y=\"resid_log\", scatter=False, lowess=True,\n            line_kws={\"color\":\"#009E73\"}, ax=axes[0])\naxes[0].axhline(0, color=\"black\", linewidth=1)\naxes[0].set_title(\"Residuals Against Fitted Values\")\naxes[0].set_xlabel(\"Log Affordability Salary\")\naxes[0].set_ylabel(\"Residual\")\n\nstats.probplot(reg[\"resid_log\"], dist=\"norm\", plot=axes[1])\naxes[1].set_title(\"QQ plot\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Log model diagnostics, same layout as the level model. The smoother lies close to zero, the spread is near constant, and the QQ plot tracks the diagonal through most of its range, showing the transformation resolves most of the level model's failure.](capstone_files/figure-html/fig-log-diag-output-1.png){#fig-log-diag width=826 height=346}\n:::\n:::\n\n\n:::{#fc3f28cd .cell .markdown}\nThe smoothed residual line doesn’t lie perfectly flat even after the transformation. The remaining deviations are structured in a way that a single global transformation cannot absorb, most likely due to interactions among the inputs. These deviations motivate the increase in model complexity.\n\n## Variance decomposition\n\nAffordability, salary, and task groups vary both across counties and within a county over time. These variations have different implications. The two manual groups show almost complete variation between counties, with only 10-25% variation within a county on the corrected window. This makes the associated affordability differences more durable rather than temporary. Routine cognitive is the only group with genuine within-county movement, with nearly half of its variation on the corrected window.\n\nThe Census occupation coding change between 2009 and 2010, as described in @sec-data, inflates apparent within-county variation for the routine cognitive group. This is due to the way the source data were coded, not a property of the counties. Therefore, we repeat the main estimates on a panel restricted to 2010 onward and additionally on pre-pandemic (2010-2019) and post-pandemic (2021-2023) windows. Coefficient stability across these windows is reported in @sec-results, along with the between- versus within-county exhibits that support the claim of persistence.\n\n## Predictive Modeling\n\nBeyond the inferential panel regression above, we evaluate three predictive\napproaches of increasing complexity: linear regression, Random Forest, and a\nsmall neural net. We check whether a flexible model captures meaningfully more\nsignal than the linear specification. We reuse the county-year panel already\nassembled above, extended with state identifiers for the fixed effects\ncomparison below.\n:::\n\n::: {#db9fa7e5 .cell .hidden execution_count=6}\n``` {.python .cell-code .hidden}\n# state_code isn't in the panel regression's df, add it here\nstate_lookup = pd.read_sql(\n    \"select county_fips, state_code from county\", engine\n)\ndf_ml = df.merge(state_lookup, on=\"county_fips\", how=\"left\")\n```\n:::\n\n\n:::{#2b5cd7d3 .cell .markdown}\n### Feature set and reference categories\n:::\n\n::: {#8c9c6753 .cell .hidden execution_count=7}\n``` {.python .cell-code .hidden}\nfeature_cols = [\n    \"routine_cognitive_share\",\n    \"routine_manual_share\",\n    \"non_routine_cognitive_share\",\n    \"non_routine_manual_share\",\n    \"poverty_rate\",\n    \"unemployment_rate\",\n    \"year\",\n    \"state_code\",\n]\n\nmodel_df = df_ml.dropna(subset=feature_cols).copy()\nmodel_df[feature_cols].describe(include=\"all\").T\n```\n\n::: {.cell-output .cell-output-display execution_count=75}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>unique</th>\n      <th>top</th>\n      <th>freq</th>\n      <th>mean</th>\n      <th>std</th>\n      <th>min</th>\n      <th>25%</th>\n      <th>50%</th>\n      <th>75%</th>\n      <th>max</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>routine_cognitive_share</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>0.220513</td>\n      <td>0.040156</td>\n      <td>0.08639</td>\n      <td>0.194756</td>\n      <td>0.225085</td>\n      <td>0.249971</td>\n      <td>0.382689</td>\n    </tr>\n    <tr>\n      <th>routine_manual_share</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>0.197688</td>\n      <td>0.05794</td>\n      <td>0.034704</td>\n      <td>0.155106</td>\n      <td>0.192944</td>\n      <td>0.236143</td>\n      <td>0.444236</td>\n    </tr>\n    <tr>\n      <th>non_routine_cognitive_share</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>0.336645</td>\n      <td>0.077423</td>\n      <td>0.151628</td>\n      <td>0.280571</td>\n      <td>0.325999</td>\n      <td>0.382112</td>\n      <td>0.748424</td>\n    </tr>\n    <tr>\n      <th>non_routine_manual_share</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>0.245154</td>\n      <td>0.041032</td>\n      <td>0.094918</td>\n      <td>0.21763</td>\n      <td>0.243669</td>\n      <td>0.271164</td>\n      <td>0.445359</td>\n    </tr>\n    <tr>\n      <th>poverty_rate</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>13.810256</td>\n      <td>5.135316</td>\n      <td>2.6</td>\n      <td>10.1</td>\n      <td>13.5</td>\n      <td>17.0</td>\n      <td>40.3</td>\n    </tr>\n    <tr>\n      <th>unemployment_rate</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>5.89854</td>\n      <td>2.735315</td>\n      <td>1.5</td>\n      <td>3.8</td>\n      <td>5.3</td>\n      <td>7.4</td>\n      <td>29.1</td>\n    </tr>\n    <tr>\n      <th>year</th>\n      <td>11983.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2015.276058</td>\n      <td>4.601049</td>\n      <td>2008.0</td>\n      <td>2011.0</td>\n      <td>2015.0</td>\n      <td>2019.0</td>\n      <td>2023.0</td>\n    </tr>\n    <tr>\n      <th>state_code</th>\n      <td>11983</td>\n      <td>49</td>\n      <td>48</td>\n      <td>762</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{#f9ad8c0a .cell .markdown}\nTask shares are computed directly by the database as each category's count\ndivided by the four-category sum, so they already satisfy the constraint used\nin the panel regression above and require no additional normalization here.\nAs before, one category must be dropped to avoid a deterministic column, and\nwe retain `non_routine_cognitive_share` as the omitted reference for\nconsistency with the panel regression.\n\n### Year and state dummies\n\nRunning year as a factor, not as numeric, gives each year its own independent\ncoefficient, with no assumption about ordering or spacing between them.\n\nLeaving one state as a reference state as well, which will be the median\naffordability state, whatever that may be in our data.\n:::\n\n::: {#2eac1072 .cell execution_count=8}\n``` {.python .cell-code .hidden}\nmodel_df[\"year\"] = model_df[\"year\"].astype(\"category\")\nmodel_df[\"state_code\"] = model_df[\"state_code\"].astype(\"category\")\n\nREFERENCE_YEAR = model_df[\"year\"].cat.categories.min()      # earliest year as reference\n\n# Pool states with too few counties to support a stable, independent coefficient\ncounty_counts = model_df.groupby(\"state_code\", observed=True)[\"county_fips\"].nunique()\nTHIN_STATE_THRESHOLD = 5\nthin_states = county_counts[county_counts < THIN_STATE_THRESHOLD].index.tolist()\nprint(\"States pooled into 'OTHER' (fewer than\", THIN_STATE_THRESHOLD, \"counties):\", thin_states)\n\nmodel_df[\"state_code_grouped\"] = model_df[\"state_code\"].astype(str)\nmodel_df[\"state_code_grouped\"] = model_df[\"state_code_grouped\"].where(\n    ~model_df[\"state_code_grouped\"].isin(thin_states), \"OTHER\"\n)\nmodel_df[\"state_code_grouped\"] = model_df[\"state_code_grouped\"].astype(\"category\")\n\nstate_affordability = model_df.groupby(\"state_code_grouped\", observed=True)[\"affordability_salary\"].mean().sort_values()\nprint(state_affordability)\n\nmedian_state = state_affordability.index[len(state_affordability) // 2]\nprint(\"\\nState/group closest to median affordability:\", median_state)\n\nREFERENCE_STATE = median_state\n\nyear_dummies = pd.get_dummies(model_df[\"year\"], prefix=\"year\")\nyear_dummies = year_dummies.drop(columns=[f\"year_{REFERENCE_YEAR}\"])\n\nstate_dummies = pd.get_dummies(model_df[\"state_code_grouped\"], prefix=\"state\")\nstate_dummies = state_dummies.drop(columns=[f\"state_{REFERENCE_STATE}\"])\n\nmodel_df = pd.concat([model_df, year_dummies, state_dummies], axis=1)\n\nyear_cols_model = list(year_dummies.columns)\nstate_cols_model = list(state_dummies.columns)\n\nprint(\"Year dummy columns:\", year_cols_model)\nprint(\"Number of state dummy columns:\", len(state_cols_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStates pooled into 'OTHER' (fewer than 5 counties): ['02', '10', '15', '31', '32', '38', '44', '46', '50', '56']\nstate_code_grouped\n04       49162.399048\n35       51120.150650\n54       51612.794808\n12       53792.854948\n45       54053.901136\n22       54540.841406\n23       54883.638111\n05       55211.965697\n37       55284.510559\n01       55354.050163\n41       55387.832098\n28       56112.461608\n42       57701.695436\n16       57767.458000\n26       58288.849932\n36       58523.412069\n40       58552.186364\n53       58731.325139\n30       59131.600588\n39       59250.894861\n48       59699.104475\n13       60044.603800\n18       60127.991175\n47       60180.907811\n21       60525.209278\n06       61605.522315\n29       61665.309602\n17       61803.834076\n20       62548.987203\n19       65244.072027\n25       65694.014278\nOTHER    65850.986514\n55       65923.985812\n33       66527.155934\n08       69039.754624\n49       69260.277813\n34       71775.309619\n51       72636.249933\n24       75561.805000\n27       76705.249375\nName: affordability_salary, dtype: float64\n\nState/group closest to median affordability: 48\nYear dummy columns: ['year_2009', 'year_2010', 'year_2011', 'year_2012', 'year_2013', 'year_2014', 'year_2015', 'year_2016', 'year_2017', 'year_2018', 'year_2019', 'year_2021', 'year_2022', 'year_2023']\nNumber of state dummy columns: 39\n```\n:::\n:::\n\n\n:::{#99658122 .cell .markdown}\nHere we identify every state with fewer than 5 distinct counties in our data\nand relabel them as \"OTHER.\" They can't reliably support their own\nindependent coefficient otherwise.\n\nTexas was selected as the reference state because its mean affordability sits\nclosest to the panel median. It's not a cost-of-living outlier in either\ndirection, and it has enormous within-state diversity: major metros like\nAustin/Dallas/Houston alongside a huge number of rural counties. So,\n\"different from Texas\" is a fairly intuitive baseline for other states to be\nread against.\n:::\n\n::: {#cell-fig-state-afford .cell execution_count=9}\n``` {.python .cell-code .hidden}\nstate_affordability.plot(kind=\"bar\", figsize=(14, 4))\nplt.axhline(state_affordability.median(), color=\"red\", linestyle=\"--\", label=\"Median\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Mean affordability salary by state, sorted ascending, with the panel median marked. Texas sits near the middle of the distribution, supporting its use as the reference state.](capstone_files/figure-html/fig-state-afford-output-1.png){#fig-state-afford width=1155 height=458}\n:::\n:::\n\n\n:::{#5dd1ce17 .cell .markdown}\nFigure @fig-state-afford shows that Texas lies near the middle of the states\nin terms of affordability and is usable as a reference point.\n\n### Collinearity check\n\nOur four main features — `routine_cognitive_share`, `routine_manual_share`,\n`non_routine_cognitive_share`, `non_routine_manual_share` — are shares of a\nwhole, thus we need to remove one in order to maintain independence (as the\nfourth is deterministic once you know the values of the other three). If we\ndidn't remove one, then one feature for certain would be a VIF offender.\n\nThe remaining three coefficients become interpretable as: the effect of\nshifting share toward this category, away from the omitted one.\n:::\n\n::: {#a13dad67 .cell execution_count=10}\n``` {.python .cell-code .hidden}\nexposure_check_cols = [\"routine_cognitive_share\",\n    \"routine_manual_share\",\n    \"non_routine_cognitive_share\",\n    \"non_routine_manual_share\"]\n\nREFERENCE_EXPOSURE = \"non_routine_cognitive_share\"\nexposure_cols_model = [c for c in exposure_check_cols if c != REFERENCE_EXPOSURE]\ncore_features = exposure_cols_model + [\"poverty_rate\", \"unemployment_rate\"]\nprint(\"Exposure scores entering the model:\", exposure_cols_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nExposure scores entering the model: ['routine_cognitive_share', 'routine_manual_share', 'non_routine_manual_share']\n```\n:::\n:::\n\n\n::: {#tbl-vif-ml .cell tbl-cap='Variance inflation factors for year and state dummies after removing the reference exposure category. All values fall below 5, indicating no remaining collinearity concern.' execution_count=11}\n``` {.python .cell-code .hidden}\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor\nimport statsmodels.api as sm\n\nvif_features = core_features + year_cols_model + state_cols_model\n\nX_vif = sm.add_constant(model_df[vif_features].astype(float))\n\nvif_data = pd.DataFrame({\n    \"feature\": X_vif.columns,\n    \"VIF\": [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])],\n})\nvif_data[vif_data[\"feature\"].isin(year_cols_model + state_cols_model)].sort_values(\"VIF\", ascending=False).head(10)\n```\n\n::: {.cell-output .cell-output-display execution_count=79}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>feature</th>\n      <th>VIF</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>7</th>\n      <td>year_2010</td>\n      <td>3.670674</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>year_2011</td>\n      <td>3.370305</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>year_2012</td>\n      <td>3.284874</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>year_2013</td>\n      <td>3.166672</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>year_2014</td>\n      <td>3.023630</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>year_2015</td>\n      <td>2.963071</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>year_2016</td>\n      <td>2.904967</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>year_2017</td>\n      <td>2.851808</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>year_2018</td>\n      <td>2.580857</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>year_2022</td>\n      <td>2.531588</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{#f93133e4 .cell .markdown}\n@tbl-vif-ml lists the highest variance inflation factors after removal of\n`non_routine_cognitive_share`; no offender columns remain, as all features\nhave VIF < 5.\n\n### Train/test split (grouped by county)\n\nNot forecasting, so a time-ordered split isn't required for its usual reason.\nBut we do want a grouped split because a county's economic profile likely\nbarely moves year to year, so its 2018 and 2019 rows are near-duplicates.\nObviously, this is a problem, as if two sequential rows end up in opposite\nsplits, the model can just memorize rather than learn relationships. So, we\nwill group by `county_fips` when splitting to force every test-set prediction\nto come from a county the model has never seen a single row of. This ensures\na test of whether the pattern is relationship driven rather than memorized.\n:::\n\n::: {#64972d58 .cell .hidden execution_count=12}\n``` {.python .cell-code .hidden}\nfrom sklearn.model_selection import GroupShuffleSplit\nfrom sklearn.metrics import r2_score, mean_absolute_error\nfrom sklearn.preprocessing import StandardScaler\n\nfeature_cols_reg = core_features + year_cols_model + state_cols_model\ntarget_col = \"affordability_salary\"\n\n\nX = model_df[feature_cols_reg].reset_index(drop=True).astype(float)\ny = model_df[target_col].reset_index(drop=True)\ngroups = model_df[\"county_fips\"].reset_index(drop=True)\n\n# quick skew check on the target -- log-transform candidate\nprint(\"Target skew:\", y.skew())\n\ngss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)\ntrain_idx, test_idx = next(gss.split(X, y, groups))\n\nX_train, X_test = X.iloc[train_idx], X.iloc[test_idx]\ny_train, y_test = y.iloc[train_idx], y.iloc[test_idx]\ngroups_train = groups.iloc[train_idx]\n\nprint(\"Train rows:\", len(X_train), \" Test rows:\", len(X_test))\nprint(\"Overlap in county_fips between train/test (should be 0):\",\n      len(set(groups.iloc[train_idx]) & set(groups.iloc[test_idx])))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTarget skew: 1.1788406079511708\nTrain rows: 9565  Test rows: 2418\nOverlap in county_fips between train/test (should be 0): 0\n```\n:::\n:::\n\n\n::: {#644d0c87 .cell .hidden execution_count=13}\n``` {.python .cell-code .hidden}\n# Baseline feature set (no year/state), reusing the SAME row split as the full model\nfeature_cols_base = exposure_cols_model + [\"poverty_rate\", \"unemployment_rate\"]\nX_base = model_df[feature_cols_base].reset_index(drop=True).astype(float)\nX_train_base, X_test_base = X_base.iloc[train_idx], X_base.iloc[test_idx]\n```\n:::\n\n\n:::{#c1080ee2 .cell .markdown}\n### Linear regression: baseline vs. full model\n\nWe report two versions of each linear model throughout this section: a\n**baseline** (exposure shares + poverty + unemployment only) and a **full**\nmodel (baseline + year and state controls). The baseline establishes what the\nrelationship looks like without accounting for time/geography; the full model\nis what we carry forward as our primary result, as it's the more rigorous\nversion. Including both lets us demonstrate exactly what changes when\ntime/geography are accounted for, and why.\n\n#### Baseline OLS (no year/state)\n:::\n\n::: {#dcb09840 .cell execution_count=14}\n``` {.python .cell-code .hidden}\nX_train_base_sm = sm.add_constant(X_train_base)\nols_model_base = sm.OLS(y_train, X_train_base_sm).fit()\nprint(ols_model_base.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                             OLS Regression Results                             \n================================================================================\nDep. Variable:     affordability_salary   R-squared:                       0.766\nModel:                              OLS   Adj. R-squared:                  0.766\nMethod:                   Least Squares   F-statistic:                     6249.\nDate:                  Mon, 03 Aug 2026   Prob (F-statistic):               0.00\nTime:                          19:06:07   Log-Likelihood:                -99712.\nNo. Observations:                  9565   AIC:                         1.994e+05\nDf Residuals:                      9559   BIC:                         1.995e+05\nDf Model:                             5                                         \nCovariance Type:              nonrobust                                         \n============================================================================================\n                               coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------------------\nconst                     1.507e+05    835.105    180.507      0.000    1.49e+05    1.52e+05\nroutine_cognitive_share  -8.108e+04   2222.226    -36.488      0.000   -8.54e+04   -7.67e+04\nroutine_manual_share     -7.149e+04   1524.066    -46.907      0.000   -7.45e+04   -6.85e+04\nnon_routine_manual_share -1.305e+05   2451.216    -53.259      0.000   -1.35e+05   -1.26e+05\npoverty_rate             -1376.4988     19.783    -69.582      0.000   -1415.277   -1337.721\nunemployment_rate        -1207.1783     35.209    -34.286      0.000   -1276.196   -1138.161\n==============================================================================\nOmnibus:                     1808.774   Durbin-Watson:                   0.672\nProb(Omnibus):                  0.000   Jarque-Bera (JB):             5229.433\nSkew:                           0.995   Prob(JB):                         0.00\nKurtosis:                       6.027   Cond. No.                         537.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n:::{#877fa7d8 .cell .markdown}\n(Note that features are on wildly different scales.) R² = 0.766 is\nrespectable. Every coefficient is negative and highly significant, which\nmakes sense given that non-routine cognitive was our reference, and shifting\ncounty task mix toward any of the other categories is associated with lower\naffordability (though non-routine manual is the steepest).\n\nNOTE: If we were doing predictions, the target skewness might be an issue and\na log transform would be worth considering — tabled for now since we're not\nforecasting.\n\n#### Full OLS (with year/state controls)\n:::\n\n::: {#dfd06d32 .cell execution_count=15}\n``` {.python .cell-code .hidden}\nX_train_sm = sm.add_constant(X_train)\nols_model = sm.OLS(y_train, X_train_sm).fit()\nprint(ols_model.params[core_features])\nprint(\"R-squared:\", ols_model.rsquared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nroutine_cognitive_share    -87421.198221\nroutine_manual_share       -81143.308583\nnon_routine_manual_share   -91904.212242\npoverty_rate                -1728.819845\nunemployment_rate             449.763793\ndtype: float64\nR-squared: 0.870637303564147\n```\n:::\n:::\n\n\n:::{#6fdb0936 .cell .markdown}\nWith the addition of time and geography, the R² increased from 0.766 to 0.871\nin the same model, implying that these variables explain real variance.\nNotably, the `unemployment_rate` coefficient flips sign, meaning that the\nbaseline coefficient likely absorbed some of the geography and time\nconfounding. This makes sense as unemployment-heavy places/times also tend to\nbe low-affordability places/times. The full model's coefficient reflects the\nwithin-state-year relationship instead. Also notable, the exposure mix\ncoefficients maintained their direction and relative ordering through the\naddition of the new features.\n\nFigure @fig-ols-diag shows both diagnostics side by side.\n:::\n\n::: {#cell-fig-ols-diag .cell execution_count=16}\n``` {.python .cell-code .hidden}\nimport scipy.stats as stats\n\nfitted_ols = ols_model.predict(X_train_sm)\nresiduals_ols = y_train - fitted_ols\n\nfig, axes = plt.subplots(1, 2, figsize=(9, 4))\n\naxes[0].scatter(fitted_ols, residuals_ols, alpha=0.3, s=10)\naxes[0].axhline(0, color=\"red\", linestyle=\"--\")\naxes[0].set_xlabel(\"Fitted values\")\naxes[0].set_ylabel(\"Residuals\")\naxes[0].set_title(\"Residuals Against Fitted Values\")\n\nstats.probplot(residuals_ols, dist=\"norm\", plot=axes[1])\naxes[1].set_title(\"QQ Plot\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Full raw-target OLS diagnostics. Left: residuals against fitted values; the U-shaped pattern shows the model underpredicting at both extremes. Right: QQ plot of residuals, deviating from normality in the upper tail.](capstone_files/figure-html/fig-ols-diag-output-1.png){#fig-ols-diag width=804 height=346}\n:::\n:::\n\n\n:::{#f1e74512 .cell .markdown}\nThere is a clear U-shaped pattern to the residual plot, indicating that the\nresiduals are not uniformly distributed, thus the OLS is not a reliable model\nfor our data with the target as is.\n\n#### Full OLS (with year/state controls) and log target\n\nThe binned affordability salary vs. affordability salary graphs showed an\napproximate exponential pattern, so we will investigate whether logging the\ntarget will make a linear model more appropriate.\n:::\n\n::: {#f1ce85c0 .cell execution_count=17}\n``` {.python .cell-code .hidden}\nprint(\"Any zero/negative affordability values?\", (y <= 0).sum())  # confirm log is safe\n\ny_train_log = np.log(y_train)\ny_test_log = np.log(y_test)\n\nprint(\"Skew, original:\", y_train.skew())\nprint(\"Skew, logged:  \", y_train_log.skew())\n\nols_model_log = sm.OLS(y_train_log, X_train_sm).fit()\nprint(ols_model_log.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAny zero/negative affordability values? 0\nSkew, original: 1.2324330032097133\nSkew, logged:   0.458530959523057\n                             OLS Regression Results                             \n================================================================================\nDep. Variable:     affordability_salary   R-squared:                       0.913\nModel:                              OLS   Adj. R-squared:                  0.912\nMethod:                   Least Squares   F-statistic:                     1718.\nDate:                  Mon, 03 Aug 2026   Prob (F-statistic):               0.00\nTime:                          19:06:08   Log-Likelihood:                 10999.\nNo. Observations:                  9565   AIC:                        -2.188e+04\nDf Residuals:                      9506   BIC:                        -2.146e+04\nDf Model:                            58                                         \nCovariance Type:              nonrobust                                         \n============================================================================================\n                               coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------------------\nconst                       12.0395      0.010   1192.954      0.000      12.020      12.059\nroutine_cognitive_share     -1.0795      0.034    -31.520      0.000      -1.147      -1.012\nroutine_manual_share        -1.0892      0.017    -65.839      0.000      -1.122      -1.057\nnon_routine_manual_share    -1.2127      0.027    -45.269      0.000      -1.265      -1.160\npoverty_rate                -0.0291      0.000   -132.649      0.000      -0.030      -0.029\nunemployment_rate            0.0008      0.001      1.315      0.189      -0.000       0.002\nyear_2009                   -0.0121      0.005     -2.481      0.013      -0.022      -0.003\nyear_2010                    0.0367      0.006      6.053      0.000       0.025       0.049\nyear_2011                    0.0587      0.006     10.082      0.000       0.047       0.070\nyear_2012                    0.0808      0.006     14.185      0.000       0.070       0.092\nyear_2013                    0.0986      0.006     17.632      0.000       0.088       0.110\nyear_2014                    0.1119      0.005     20.483      0.000       0.101       0.123\nyear_2015                    0.1221      0.005     22.627      0.000       0.112       0.133\nyear_2016                    0.1314      0.005     24.519      0.000       0.121       0.142\nyear_2017                    0.1483      0.005     28.076      0.000       0.138       0.159\nyear_2018                    0.1708      0.005     33.885      0.000       0.161       0.181\nyear_2019                    0.1962      0.005     39.767      0.000       0.187       0.206\nyear_2021                    0.2320      0.005     47.543      0.000       0.222       0.242\nyear_2022                    0.2984      0.005     60.072      0.000       0.289       0.308\nyear_2023                    0.3233      0.005     66.363      0.000       0.314       0.333\nstate_01                    -0.0100      0.006     -1.720      0.086      -0.021       0.001\nstate_04                    -0.0424      0.009     -4.744      0.000      -0.060      -0.025\nstate_05                    -0.0378      0.007     -5.401      0.000      -0.052      -0.024\nstate_06                    -0.0066      0.005     -1.252      0.211      -0.017       0.004\nstate_08                    -0.0685      0.007     -9.437      0.000      -0.083      -0.054\nstate_12                    -0.1287      0.005    -26.686      0.000      -0.138      -0.119\nstate_13                     0.0065      0.005      1.390      0.165      -0.003       0.016\nstate_16                    -0.0715      0.009     -8.235      0.000      -0.088      -0.054\nstate_17                    -0.0388      0.006     -6.211      0.000      -0.051      -0.027\nstate_18                    -0.0376      0.005     -7.075      0.000      -0.048      -0.027\nstate_19                    -0.0171      0.008     -2.086      0.037      -0.033      -0.001\nstate_20                    -0.0419      0.009     -4.782      0.000      -0.059      -0.025\nstate_21                    -0.0118      0.006     -1.868      0.062      -0.024       0.001\nstate_22                     0.0186      0.006      2.912      0.004       0.006       0.031\nstate_23                    -0.1901      0.012    -16.006      0.000      -0.213      -0.167\nstate_24                    -0.0332      0.007     -5.103      0.000      -0.046      -0.020\nstate_25                    -0.1004      0.007    -14.046      0.000      -0.114      -0.086\nstate_26                    -0.0488      0.005     -8.920      0.000      -0.060      -0.038\nstate_27                    -0.0035      0.007     -0.501      0.617      -0.017       0.010\nstate_28                     0.0060      0.007      0.805      0.421      -0.009       0.021\nstate_29                    -0.0494      0.006     -8.577      0.000      -0.061      -0.038\nstate_30                    -0.1131      0.010    -11.639      0.000      -0.132      -0.094\nstate_33                    -0.1528      0.009    -16.217      0.000      -0.171      -0.134\nstate_34                    -0.0543      0.006     -8.637      0.000      -0.067      -0.042\nstate_35                    -0.0016      0.010     -0.168      0.867      -0.021       0.017\nstate_36                    -0.1117      0.005    -22.893      0.000      -0.121      -0.102\nstate_37                    -0.0613      0.005    -13.070      0.000      -0.071      -0.052\nstate_39                    -0.0408      0.005     -8.530      0.000      -0.050      -0.031\nstate_40                    -0.0128      0.007     -1.892      0.059      -0.026       0.000\nstate_41                    -0.0950      0.006    -14.849      0.000      -0.107      -0.082\nstate_42                    -0.1086      0.005    -22.748      0.000      -0.118      -0.099\nstate_45                    -0.0487      0.006     -8.234      0.000      -0.060      -0.037\nstate_47                    -0.0375      0.006     -6.518      0.000      -0.049      -0.026\nstate_49                    -0.0180      0.010     -1.796      0.073      -0.038       0.002\nstate_51                    -0.0480      0.005     -9.412      0.000      -0.058      -0.038\nstate_53                    -0.0697      0.007    -10.148      0.000      -0.083      -0.056\nstate_54                    -0.0796      0.009     -9.107      0.000      -0.097      -0.062\nstate_55                    -0.0430      0.006     -7.553      0.000      -0.054      -0.032\nstate_OTHER                 -0.0343      0.005     -6.334      0.000      -0.045      -0.024\n==============================================================================\nOmnibus:                      183.701   Durbin-Watson:                   0.677\nProb(Omnibus):                  0.000   Jarque-Bera (JB):              316.447\nSkew:                           0.160   Prob(JB):                     1.92e-69\nKurtosis:                       3.832   Cond. No.                         747.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n:::{#30818a11 .cell .markdown}\nFigure @fig-ols-log-diag shows the same pair of diagnostics for the\nlog-target specification.\n:::\n\n::: {#cell-fig-ols-log-diag .cell execution_count=18}\n``` {.python .cell-code .hidden}\nresiduals_log = y_train_log - ols_model_log.predict(X_train_sm)\n\nfig, axes = plt.subplots(1, 2, figsize=(9, 4))\n\naxes[0].scatter(ols_model_log.predict(X_train_sm), residuals_log, alpha=0.3, s=10)\naxes[0].axhline(0, color=\"red\", linestyle=\"--\")\naxes[0].set_xlabel(\"Fitted (log)\")\naxes[0].set_ylabel(\"Residuals (log)\")\naxes[0].set_title(\"Residuals Against Fitted Values\")\n\nstats.probplot(residuals_log, dist=\"norm\", plot=axes[1])\naxes[1].set_title(\"QQ Plot\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Log-target OLS diagnostics, same layout as the raw-target model. The residual spread is roughly constant across fitted values and the QQ plot tracks the diagonal much more closely.](capstone_files/figure-html/fig-ols-log-diag-output-1.png){#fig-ols-log-diag width=826 height=346}\n:::\n:::\n\n\n:::{#b033cf5e .cell .markdown}\nThe residual plot looks uniformly distributed and the QQ plot follows a\nstraight line pattern, so with a logged target we can use a linear model.\n:::\n\n::: {#bd892302 .cell execution_count=19}\n``` {.python .cell-code .hidden}\nprint(\"R-squared (log target, in-sample):\", ols_model_log.rsquared)\n\nX_test_sm = sm.add_constant(X_test, has_constant=\"add\")\ny_pred_ols_log = ols_model_log.predict(X_test_sm)\n\nprint(\"Test R2 (log space):\", r2_score(y_test_log, y_pred_ols_log))\n\ny_pred_ols_log_dollars = np.exp(y_pred_ols_log)\nprint(\"Test R2 (back-transformed to $):\", r2_score(y_test, y_pred_ols_log_dollars))\nprint(\"Test MAE (back-transformed to $):\", mean_absolute_error(y_test, y_pred_ols_log_dollars))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR-squared (log target, in-sample): 0.9128887327038346\nTest R2 (log space): 0.8894251280521438\nTest R2 (back-transformed to $): 0.8957661959388022\nTest MAE (back-transformed to $): 3635.5329144913035\n```\n:::\n:::\n\n\n:::{#fde20895 .cell .markdown}\nWith a logged target, the model achieves an in-sample R² of 0.913 and a\nheld-out test R² (transformed back into dollars) of 0.896. Both are notably\nhigher than the raw-target model's 0.871, and with valid residual\ndiagnostics.\n\n#### Baseline vs. full comparison table\n:::\n\n::: {#tbl-ols-comparison .cell tbl-cap='Coefficients across the baseline, full raw-target, and full log-target OLS specifications, with log-target coefficients also converted to percent change per one-point shift.' execution_count=20}\n``` {.python .cell-code .hidden}\ncomparison_ols = pd.DataFrame({\n    \"baseline\": ols_model_base.params,\n    \"with_controls (raw $)\": ols_model.params[feature_cols_base],\n    \"with_controls (log target)\": ols_model_log.params[feature_cols_base],\n})\n\nlog_coefs = ols_model_log.params[feature_cols_base]\n\n# exposure shares are 0-1 scale (1pp = 0.01 units); poverty/unemployment are already in point units (1pp = 1 unit)\nunit_per_point = {\n    \"routine_cognitive_share\": 0.01,\n    \"routine_manual_share\": 0.01,\n    \"non_routine_manual_share\": 0.01,\n    \"poverty_rate\": 1.0,\n    \"unemployment_rate\": 1.0,\n}\n\npct_change_per_point = {\n    feat: (np.exp(log_coefs[feat] * unit_per_point[feat]) - 1) * 100\n    for feat in feature_cols_base\n}\n\ncomparison_ols[\"log_target (% change per 1pp)\"] = pd.Series(pct_change_per_point)\ncomparison_ols\n```\n\n::: {.cell-output .cell-output-display execution_count=88}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>baseline</th>\n      <th>with_controls (raw $)</th>\n      <th>with_controls (log target)</th>\n      <th>log_target (% change per 1pp)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>const</th>\n      <td>150742.645766</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>non_routine_manual_share</th>\n      <td>-130549.425753</td>\n      <td>-91904.212242</td>\n      <td>-1.212747</td>\n      <td>-1.205423</td>\n    </tr>\n    <tr>\n      <th>poverty_rate</th>\n      <td>-1376.498808</td>\n      <td>-1728.819845</td>\n      <td>-0.029121</td>\n      <td>-2.870075</td>\n    </tr>\n    <tr>\n      <th>routine_cognitive_share</th>\n      <td>-81084.753276</td>\n      <td>-87421.198221</td>\n      <td>-1.079544</td>\n      <td>-1.073738</td>\n    </tr>\n    <tr>\n      <th>routine_manual_share</th>\n      <td>-71490.091428</td>\n      <td>-81143.308583</td>\n      <td>-1.089197</td>\n      <td>-1.083287</td>\n    </tr>\n    <tr>\n      <th>unemployment_rate</th>\n      <td>-1207.178313</td>\n      <td>449.763793</td>\n      <td>0.000803</td>\n      <td>0.080349</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{#0a5bf569 .cell .markdown}\nAs @tbl-ols-comparison shows, `unemployment_rate`'s sign flip is confirmed\nacross all three fitted forms. Exposure coefficients shrink in magnitude from\nbaseline to raw-controls while `poverty_rate` grows (−1,376.50 → −1,728.82).\n\nEach additional percentage point of poverty rate is associated with roughly a\n2.9% decrease in affordability, holding time, geography, and task-mix fixed.\nThis is a considerably larger proportional effect than any single task-mix\ncategory.\n:::\n\n::: {#tbl-ols-r2-summary .cell tbl-cap='R-squared by specification stage: baseline, full raw-target (diagnostics failed), and full log-target.' execution_count=21}\n``` {.python .cell-code .hidden}\nr2_summary = pd.DataFrame({\n    \"model\": [\"Baseline OLS\", \"Full OLS (raw $, diagnostics failed)\", \"Full OLS (log target)\"],\n    \"r2_or_note\": [ols_model_base.rsquared, ols_model.rsquared, ols_model_log.rsquared],\n})\nr2_summary\n```\n\n::: {.cell-output .cell-output-display execution_count=89}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>model</th>\n      <th>r2_or_note</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Baseline OLS</td>\n      <td>0.765744</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Full OLS (raw $, diagnostics failed)</td>\n      <td>0.870637</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Full OLS (log target)</td>\n      <td>0.912889</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{#35334788 .cell .markdown}\n@tbl-ols-r2-summary shows R² climbing through each stage of this analysis. First, adding year and state\ncontrols to the baseline model (0.766 → 0.871) confirms that time and\ngeography explain real, previously unmodeled variance. Logging the target\n(0.871 → 0.913 in-sample, 0.896 held-out) accounts for even more variance once\nthe residual violations from the raw-target model are resolved. This is the\nmodel used for inference going forward, since the raw-target model's\ncoefficient significance cannot be trusted given its failed residual\ndiagnostics above.\n\n### Random Forest\n\nFor a Random Forest (RF), we performed a grid search using `n_estimators`,\n`max_depth`, `min_samples_leaf`, and `max_features` over the grid shown\nbelow. Given a high number of estimators to reduce variance, and\n`max_depth`/`min_samples_leaf` to add potential regularization.\n:::\n\n::: {#acd66554 .cell execution_count=22}\n``` {.python .cell-code .hidden}\n# Grid search actually run once; shown here for documentation of the search\n# space. Not re-executed on every render — see the following chunk for the\n# cached result.\n\nfrom sklearn.ensemble import RandomForestRegressor\nfrom sklearn.model_selection import GridSearchCV, GroupKFold\n\nrf = RandomForestRegressor(random_state=42, n_jobs=-1)\n\nparam_grid = {\n    \"n_estimators\": [600, 1000],\n    \"max_depth\": [None, 10, 20],\n    \"min_samples_leaf\": [1, 2, 5],\n    \"max_features\": [1.0, \"sqrt\", 0.5],\n}\n\ngroup_cv = GroupKFold(n_splits=5)\ngcv = GridSearchCV(rf, param_grid, cv=group_cv, scoring=\"r2\", n_jobs=-1)\ngcv.fit(X_train, y_train, groups=groups_train)\n\nprint(\"Best params:\", gcv.best_params_)\n```\n:::\n\n\n::: {#6cc9794e .cell .hidden execution_count=23}\n``` {.python .cell-code .hidden}\nfrom sklearn.ensemble import RandomForestRegressor\nfrom sklearn.inspection import permutation_importance\n\n# Grid search above was run once over the full param_grid; best params found were: \n# {'max_depth': None, 'max_features': 0.5, 'min_samples_leaf': 1, 'n_estimators': 1000}\n# Hardcoded here to avoid re-running an expensive search on every render.\nbest_params = {\n    \"max_depth\": None,\n    \"max_features\": 0.5,\n    \"min_samples_leaf\": 1,\n    \"n_estimators\": 1000,\n}\n\nbest_rf = RandomForestRegressor(**best_params, random_state=42, n_jobs=2)\nbest_rf.fit(X_train, y_train)\n\ny_pred_rf = best_rf.predict(X_test)\nprint(\"Test R2: \", r2_score(y_test, y_pred_rf))\nprint(\"Test MAE:\", mean_absolute_error(y_test, y_pred_rf))\n\n# overfitting check\nprint(\"Train R2:\", best_rf.score(X_train, y_train))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTest R2:  0.8762409382895193\nTest MAE: 3943.0577717617894\nTrain R2: 0.9891762932802247\n```\n:::\n:::\n\n\n:::{#496d1982 .cell .markdown}\nAn R² of 0.876 is higher than the raw-target OLS model (0.871), suggesting at\nleast some non-linear relationship in the data at this stage. However, as\nshown above, this comparison changes once the target is log-transformed,\nwhich will be addressed in the comparison below.\n\nA train/test gap of 0.989 vs. 0.876 tells us that the ceiling on this feature\nset is being constrained by something other than hyperparameters. We are\nalready fitting training data about as well as a tree ensemble can, we just\naren't getting better generalization.\n:::\n\n::: {#cell-fig-rf-resid .cell execution_count=24}\n``` {.python .cell-code .hidden}\nresiduals_rf = y_test - y_pred_rf\n\nplt.figure(figsize=(7, 5))\nplt.scatter(y_pred_rf, residuals_rf, alpha=0.3, s=10, color=\"green\")\nplt.axhline(0, color=\"red\", linestyle=\"--\")\nplt.xlabel(\"Predicted values\")\nplt.ylabel(\"Residuals\")\nplt.title(\"Random Forest residuals vs. predicted (test)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Random Forest residuals against predicted values on the held-out test set. No systematic curve or trend is visible across the range of predictions.](capstone_files/figure-html/fig-rf-resid-output-1.png){#fig-rf-resid width=672 height=442}\n:::\n:::\n\n\n:::{#8ce25f0b .cell .markdown}\nUnlike the raw-target OLS residuals, Figure @fig-rf-resid shows Random\nForest's residuals with no systematic curve or trend across the range of\npredicted values.\n:::\n\n::: {#49dd77a8 .cell .hidden execution_count=25}\n``` {.python .cell-code .hidden}\n# perm_imp = permutation_importance(\n#     best_rf, X_test, y_test, n_repeats=20, random_state=42, n_jobs=1\n# )\n```\n:::\n\n\n:::{#7f54897e .cell .markdown}\n##### Ablation test\n:::\n\n::: {#2a7aac79 .cell execution_count=26}\n``` {.python .cell-code .hidden}\nfeature_cols_no_exposure = [c for c in feature_cols_reg if c not in exposure_cols_model]\nX_train_ne = X_train[feature_cols_no_exposure]\nX_test_ne = X_test[feature_cols_no_exposure]\n\nrf_no_exposure = RandomForestRegressor(**best_params, random_state=42, n_jobs=-1)\nrf_no_exposure.fit(X_train_ne, y_train)\nprint(\"R2 without exposure scores:\", rf_no_exposure.score(X_test_ne, y_test))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR2 without exposure scores: 0.8339992605886773\n```\n:::\n:::\n\n\n:::{#be58814f .cell .markdown}\nWithout accounting for automatability at all, the same Random Forest achieves\nan R² of 0.834.\n\n##### Reverse ablation test\n:::\n\n::: {#8b8b0035 .cell execution_count=27}\n``` {.python .cell-code .hidden}\nfeature_cols_no_econ = [c for c in feature_cols_reg if c not in [\"poverty_rate\", \"unemployment_rate\"]]\nX_train_ne2 = X_train[feature_cols_no_econ]\nX_test_ne2 = X_test[feature_cols_no_econ]\n\nrf_no_econ = RandomForestRegressor(**best_params, random_state=42, n_jobs=-1)\nrf_no_econ.fit(X_train_ne2, y_train)\nprint(\"R2 without poverty/unemployment:\", rf_no_econ.score(X_test_ne2, y_test))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR2 without poverty/unemployment: 0.6983607085809014\n```\n:::\n:::\n\n\n:::{#3fd759a1 .cell .markdown}\nUsing only the automatability scores (excluding poverty and unemployment),\nthe model reaches an R² of 0.698 — meaningful on its own, but well short of\nthe full model.\n\n##### Testing RF with logged target\n\nLogging the target could be good for RF too, so we run that as well.\n:::\n\n::: {#2c5b9cb7 .cell execution_count=28}\n``` {.python .cell-code .hidden}\nrf_log = RandomForestRegressor(**best_params, random_state=42, n_jobs=2)\nrf_log.fit(X_train, y_train_log)\n\ny_pred_rf_log = rf_log.predict(X_test)\nprint(\"Test R2 (log space):\", r2_score(y_test_log, y_pred_rf_log))\n\ny_pred_rf_log_dollars = np.exp(y_pred_rf_log)\nprint(\"Test R2 (back-transformed to $):\", r2_score(y_test, y_pred_rf_log_dollars))\nprint(\"Test MAE (back-transformed to $):\", mean_absolute_error(y_test, y_pred_rf_log_dollars))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTest R2 (log space): 0.8781823460727236\nTest R2 (back-transformed to $): 0.8768487377842192\nTest MAE (back-transformed to $): 3916.409028061873\n```\n:::\n:::\n\n\n:::{#b055ff10 .cell .markdown}\nAn R² of 0.877 after back-transforming — a negligible change from the\nuntransformed-target model (0.876). Since the log-target model is already\nestablished as the reference model for the linear regression above, we adopt\nlog-target RF here as well for consistency in the final comparison, even\nthough the choice of target makes little practical difference for Random\nForest specifically.\n\n#### Grouped permutation — the actual \"combination\" question\n\nTo see what the four exposure scores do together, rather than one at a time\ndiluting each other, we permute all four jointly and compare the drop in R²\nto permuting them individually.\n:::\n\n::: {#badef59d .cell execution_count=29}\n``` {.python .cell-code .hidden}\nfrom sklearn.metrics import r2_score as _r2\n\nexposure_cols = exposure_cols_model  # the three non-reference exposure scores\nrng = np.random.RandomState(42)\n\nbaseline_r2 = _r2(y_test, best_rf.predict(X_test))\n\ndef grouped_permutation_drop(cols, n_repeats=20):\n    drops = []\n    for _ in range(n_repeats):\n        X_perm = X_test.copy()\n        shuffled_idx = rng.permutation(len(X_perm))\n        X_perm[cols] = X_perm[cols].values[shuffled_idx]\n        drops.append(baseline_r2 - _r2(y_test, best_rf.predict(X_perm)))\n    return np.mean(drops)\n\nprint(\"Baseline R2:\", baseline_r2)\n\njoint_drop = grouped_permutation_drop(exposure_cols)\nprint(\"Drop from permuting all exposure scores together:\", joint_drop)\n\nindividual_drops = {}\nfor col in exposure_cols:\n    individual_drops[col] = grouped_permutation_drop([col])\n    print(f\"Drop from permuting {col} alone:\", individual_drops[col])\n\nyear_drop = grouped_permutation_drop(year_cols_model)\nstate_drop = grouped_permutation_drop(state_cols_model)\nprint(\"Drop from permuting year (jointly):\", year_drop)\nprint(\"Drop from permuting state (jointly):\", state_drop)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBaseline R2: 0.8762409382895193\nDrop from permuting all exposure scores together: 0.1531310972084307\nDrop from permuting routine_cognitive_share alone: 0.025615576618095576\nDrop from permuting routine_manual_share alone: 0.03706460532391171\nDrop from permuting non_routine_manual_share alone: 0.048090402537186584\nDrop from permuting year (jointly): 0.12740689943244296\nDrop from permuting state (jointly): 0.008320346919784616\n```\n:::\n:::\n\n\n:::{#c8a63946 .cell .markdown}\nYear matters far more than state (0.127 vs. 0.008): time, not geography,\ncarries the bulk of the \"when/where\" signal once economic and exposure score\nvariables are controlled for.\n\nExposure score gross importance (0.153) is considerably larger than its\nnet/irreplaceable contribution of 0.042 from the ablation test in RF. This\nimplies that it shares (mostly) real predictive overlap with poverty,\nunemployment, and time, but still adds something those don't fully capture.\n\nAmong the three individual task shares, `non_routine_manual_share` shows the\nlargest individual sensitivity (though none of the three should be read as\nindependently additive given they are parts of a whole).\n\n### Simple neural net\n\nWe will build a simple neural net. As it is likely already a bit overkill, we\nwill keep it shallow and the layers narrow. We are still doing a regression\nand our target is continuous, so we will have a single linear output unit.\n:::\n\n::: {#e876baff .cell execution_count=30}\n``` {.python .cell-code .hidden}\nimport tensorflow as tf\nfrom tensorflow.keras import layers, models, callbacks\n\nscaler_x = StandardScaler().fit(X_train)\nX_train_s = scaler_x.transform(X_train)\nX_test_s = scaler_x.transform(X_test)\n\nscaler_y = StandardScaler().fit(y_train.values.reshape(-1, 1))\ny_train_s = scaler_y.transform(y_train.values.reshape(-1, 1)).ravel()\ny_test_s = scaler_y.transform(y_test.values.reshape(-1, 1)).ravel()\n\nn_features = X_train.shape[1]          # now ~70+ with year/state dummies\nh1 = int(round(n_features * 1.5))\nh2 = max(int(round(h1 * 0.5)), 20)\nh3 = 10                                  # latent bottleneck\n\nnn = models.Sequential([\n    layers.Input(shape=(n_features,)),\n    layers.Dense(h1, activation=\"relu\"),\n    layers.Dropout(0.2),\n    layers.Dense(h2, activation=\"relu\"),\n    layers.Dropout(0.2),\n    layers.Dense(h3, activation=\"relu\"),\n    layers.Dense(1, activation=\"linear\"),   # regression head\n])\n\nnn.compile(optimizer=\"adam\", loss=\"mse\", metrics=[\"mae\"])\n\nes = callbacks.EarlyStopping(patience=15, restore_best_weights=True)\n\nhistory = nn.fit(\n    X_train_s, y_train_s,\n    validation_split=0.2,\n    epochs=300,\n    batch_size=32,\n    callbacks=[es],\n    verbose=0,\n)\n\ny_pred_nn_s = nn.predict(X_test_s).ravel()\ny_pred_nn = scaler_y.inverse_transform(y_pred_nn_s.reshape(-1, 1)).ravel()\n\nprint(\"Test R2: \", r2_score(y_test, y_pred_nn))\nprint(\"Test MAE:\", mean_absolute_error(y_test, y_pred_nn))\nprint(\"Stopped at epoch:\", len(history.history[\"loss\"]))\nprint(\"Best val_loss achieved:\", min(history.history[\"val_loss\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-bold\"> 1/76</span> <span class=\"ansi-white-fg\">━━━━━━━━━━━━━━━━━━━━</span> <span class=\"ansi-bold\">4s</span> 63ms/step\n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n<span class=\"ansi-bold\">42/76</span> <span class=\"ansi-green-fg\">━━━━━━━━━━━</span><span class=\"ansi-white-fg\">━━━━━━━━━</span> <span class=\"ansi-bold\">0s</span> 1ms/step \n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n<span class=\"ansi-bold\">76/76</span> <span class=\"ansi-green-fg\">━━━━━━━━━━━━━━━━━━━━</span> <span class=\"ansi-bold\">0s</span> 2ms/step\n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n<span class=\"ansi-bold\">76/76</span> <span class=\"ansi-green-fg\">━━━━━━━━━━━━━━━━━━━━</span> <span class=\"ansi-bold\">0s</span> 2ms/step\n\nTest R2:  0.8432590928458205\n\nTest MAE: 4607.2755303970225\n\nStopped at epoch: 18\n\nBest val_loss achieved: 0.24777477979660034\n</pre>\n```\n:::\n\n:::\n:::\n\n\n::: {#cell-fig-nn-curve-initial .cell execution_count=31}\n``` {.python .cell-code .hidden}\nplt.plot(history.history[\"loss\"], label=\"train\")\nplt.plot(history.history[\"val_loss\"], label=\"val\")\nplt.legend(); plt.title(\"NN training curve\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Training and validation loss for the initial, unregularized neural net. Training loss plateaus below 0.1 while validation loss falls to roughly 0.2 before rising to about 0.5, indicating overfitting.](capstone_files/figure-html/fig-nn-curve-initial-output-1.png){#fig-nn-curve-initial width=609 height=453}\n:::\n:::\n\n\n:::{#ef140dfd .cell .markdown}\nFigure @fig-nn-curve-initial shows training loss decreasing steadily and\nplateauing below 0.1, while validation loss initially decreases to\napproximately 0.2 before rising to roughly 0.5, a clear indication of\noverfitting. We address this with L2 weight regularization, increased\ndropout, and a shorter early-stopping patience.\n:::\n\n::: {#f2e01cf6 .cell execution_count=32}\n``` {.python .cell-code .hidden}\nfrom tensorflow.keras import regularizers\n\nnn = models.Sequential([\n    layers.Input(shape=(n_features,)),\n    layers.Dense(h1, activation=\"relu\", kernel_regularizer=regularizers.l2(0.001)),\n    layers.Dropout(0.4),\n    layers.Dense(h2, activation=\"relu\", kernel_regularizer=regularizers.l2(0.001)),\n    layers.Dropout(0.3),\n    layers.Dense(h3, activation=\"relu\"),\n    layers.Dense(1, activation=\"linear\"),\n])\n\nnn.compile(optimizer=\"adam\", loss=\"mse\", metrics=[\"mae\"])\n\nes = callbacks.EarlyStopping(patience=8, restore_best_weights=True)\n\nhistory = nn.fit(\n    X_train_s, y_train_s,\n    validation_split=0.2,\n    epochs=300,\n    batch_size=32,\n    callbacks=[es],\n    verbose=0,\n)\n\nprint(\"Stopped at epoch:\", len(history.history[\"loss\"]))\nprint(\"Best val_loss achieved:\", min(history.history[\"val_loss\"]))\n\ny_pred_nn_s = nn.predict(X_test_s).ravel()\ny_pred_nn = scaler_y.inverse_transform(y_pred_nn_s.reshape(-1, 1)).ravel()\n\nprint(\"Test R2: \", r2_score(y_test, y_pred_nn))\nprint(\"Test MAE:\", mean_absolute_error(y_test, y_pred_nn))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>Stopped at epoch: 48\n\nBest val_loss achieved: 0.17765924334526062\n\n\n<span class=\"ansi-bold\"> 1/76</span> <span class=\"ansi-white-fg\">━━━━━━━━━━━━━━━━━━━━</span> <span class=\"ansi-bold\">3s</span> 47ms/step\n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n<span class=\"ansi-bold\">62/76</span> <span class=\"ansi-green-fg\">━━━━━━━━━━━━━━━━</span><span class=\"ansi-white-fg\">━━━━</span> <span class=\"ansi-bold\">0s</span> 822us/step\n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\n<span class=\"ansi-bold\">76/76</span> <span class=\"ansi-green-fg\">━━━━━━━━━━━━━━━━━━━━</span> <span class=\"ansi-bold\">0s</span> 1ms/step  \n\nTest R2: \n 0.8726706021904944\n\nTest MAE: 4024.4236937810174\n</pre>\n```\n:::\n\n:::\n:::\n\n\n::: {#cell-fig-nn-curve-regularized .cell execution_count=33}\n``` {.python .cell-code .hidden}\nplt.plot(history.history[\"loss\"], label=\"train\")\nplt.plot(history.history[\"val_loss\"], label=\"val\")\nplt.legend(); plt.title(\"NN training curve\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Training and validation loss after adding L2 regularization, increased dropout, and shorter early-stopping patience. The train/validation gap narrows relative to the initial model.](capstone_files/figure-html/fig-nn-curve-regularized-output-1.png){#fig-nn-curve-regularized width=592 height=453}\n:::\n:::\n\n\n:::{#984f3fad .cell .markdown}\nFigure @fig-nn-curve-regularized shows the training curve after these\nchanges. Additional tuning could likely narrow the remaining gap between training and\nvalidation loss further. However, the current results are sufficient to draw\nthe conclusion that the neural network does not outperform Random Forest or\nthe log-target linear model, both of which are substantially cheaper to fit\nand tune. Given this project's emphasis on explaining the relationship\nbetween job automatability and affordability rather than maximizing\npredictive accuracy, we do not pursue further tuning of the neural network\nand proceed with the linear and Random Forest models as our primary results.\n\n### Cross validation\n\nAfter exploring and comparing the explained variance of the three different\nmodels, we cross-validate to give the models more generalizability.\n:::\n\n::: {#tbl-cv-summary .cell tbl-cap='Mean and standard deviation of held-out R-squared across 5-fold grouped cross-validation for log-target OLS and Random Forest.' execution_count=34}\n``` {.python .cell-code .hidden}\nfrom sklearn.model_selection import GroupKFold\n\ngroup_kfold_cv = GroupKFold(n_splits=5)\ncv_results = {\"OLS (log target)\": [], \"Random Forest\": []}\n\ny_log = np.log(y)  # full-data log target, same idea as y_train_log/y_test_log\n\nfor fold, (tr_idx, val_idx) in enumerate(group_kfold_cv.split(X, y, groups)):\n    X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]\n    y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]\n    y_tr_log, y_val_log = y_log.iloc[tr_idx], y_log.iloc[val_idx]\n\n    X_tr_sm = sm.add_constant(X_tr)\n    X_val_sm = sm.add_constant(X_val, has_constant=\"add\")\n    ols_fold_log = sm.OLS(y_tr_log, X_tr_sm).fit()\n    pred_log = ols_fold_log.predict(X_val_sm)\n    r2_ols_log_dollars = r2_score(y_val, np.exp(pred_log))  # back-transformed, dollar scale\n    cv_results[\"OLS (log target)\"].append(r2_ols_log_dollars)\n\n    rf_fold = RandomForestRegressor(**best_params, random_state=42, n_jobs=-1)\n    rf_fold.fit(X_tr, y_tr)\n    r2_rf = r2_score(y_val, rf_fold.predict(X_val))\n    cv_results[\"Random Forest\"].append(r2_rf)\n\n    print(f\"Fold {fold}: OLS(log)={r2_ols_log_dollars:.3f} RF={r2_rf:.3f}\")\n\ncv_summary = pd.DataFrame({m: {\"mean_r2\": np.mean(s), \"std_r2\": np.std(s)} for m, s in cv_results.items()}).T\ncv_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFold 0: OLS(log)=0.911 RF=0.916\nFold 1: OLS(log)=0.894 RF=0.888\nFold 2: OLS(log)=0.892 RF=0.901\nFold 3: OLS(log)=0.914 RF=0.899\nFold 4: OLS(log)=0.893 RF=0.902\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=101}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean_r2</th>\n      <th>std_r2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>OLS (log target)</th>\n      <td>0.900724</td>\n      <td>0.009480</td>\n    </tr>\n    <tr>\n      <th>Random Forest</th>\n      <td>0.901373</td>\n      <td>0.008994</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{#7a37a9a2 .cell .markdown}\nAs @tbl-cv-summary shows, across 5-fold cross-validation, OLS (log target)\nand Random Forest are statistically indistinguishable (mean R² of 0.901 and\n0.901, respectively),\nwith Random Forest showing marginally lower variance across folds (std\n0.0090 vs. 0.0095). This confirms the single-split result below is not an\nartifact of one particular split, and both models generalize consistently\nand comparably across held-out counties.\n\nNote that the neural net was not included, as cross-validating would be very\nexpensive, and as noted above it will not be carried forward for that reason.\n\nModel comparison across test R² and MAE, along with the full ablation-test\ntakeaways, appears in @sec-results.\n\n## Wrap-up summary\n\nThree specifications answer three different questions. The panel regression, with\ncounty-clustered standard errors, is the model we use for inference. It tells us that\nroutine-intensive work is associated with lower affordability salary even after\ncontrolling for poverty, unemployment, time, and geography. Its log respecification\nresolves the residual violations that make the raw target version untrustworthy for\nthat purpose.\n\nThe predictive models answer the different question of how much of affordability salary\ncan be explained at all, and by what. Random Forest and the log-target linear model\nperform comparably on held-out data, which tells us the relationship's curvature adds\nlittle once poverty, unemployment, time, and geography are already in the model. The\nneural net does not improve on either, and its added complexity is not justified by\nthis feature set.\n\nAcross both approaches, task-mix shares carry real, independent explanatory power, but\npoverty rate remains the dominant single factor throughout. This ordering, not any one\nmodel's fit statistic, is the finding this analysis is built to support, and it is what\n@sec-results carries forward.\n\n\n<!--\nTODO analysis\n- confirm RESET test statistic and p-value against current model run (referenced\n  in @sec-results but not computed here)\n- restricted 2010-onward panel estimates, mentioned in Variance decomposition but\n  not yet run\nSection rules from the in class template:\n1. Cover only the models most important to understanding the results.\n2. Depth is a function of audience.\n3. If a method's output does not appear in the results, it does not belong here.\n4. Equations must be explained and referenced before they appear, and units stated.\n5. Do not narrate dead ends or the chronology of what we tried.\n-->\n\n# Results {#sec-results}\n:::\n\n::: {#332baa00 .cell .hidden execution_count=35}\n``` {.python .cell-code .hidden}\nplt.rcParams.update({\n    \"font.size\": 20,\n    \"axes.titlesize\": 20,\n    \"axes.labelsize\": 20,\n    \"xtick.labelsize\": 20,\n    \"ytick.labelsize\": 20,\n    \"legend.fontsize\": 20,\n})\n\nlabel_map = {\n    \"routine_cognitive_share\": \"Routine Cognitive\",\n    \"routine_manual_share\": \"Routine Manual\",\n    \"non_routine_manual_share\": \"Nonroutine Manual\",\n    \"poverty_rate\": \"Poverty Rate\",\n    \"unemployment_rate\": \"Unemployment\",\n}\n```\n:::\n\n\n::: {#cd4a3ac1 .cell .hidden execution_count=36}\n``` {.python .cell-code .hidden}\nresults = pd.DataFrame({\n    \"model\": [\"OLS (log target)\", \"Random Forest (log target)\", \"Neural Net\"],\n    \"test_r2\": [\n        r2_score(y_test, y_pred_ols_log_dollars),\n        r2_score(y_test, y_pred_rf_log_dollars),\n        r2_score(y_test, y_pred_nn),\n    ],\n    \"test_mae\": [\n        mean_absolute_error(y_test, y_pred_ols_log_dollars),\n        mean_absolute_error(y_test, y_pred_rf_log_dollars),\n        mean_absolute_error(y_test, y_pred_nn),\n    ],\n})\n```\n:::\n\n\n:::{#39062446 .cell .markdown}\n## Where affordability is strained\n\n<!-- FIGURE: fig-affordmap. EXISTS, poster Figure 4. Affordability salary by county,\n     averaged across the study period. Choropleth, darker means income stretches further.\n     Poster version was built on the old full frame, needs rebuilding on the 848 county\n     panel. Purpose is orientation: the outcome has geographic structure before any\n     modeling. -->\n\n<!-- FIGURE: fig-gapmap. EXISTS, poster Figure 1. Median household income minus\n     affordability salary, red where income overstates purchasing power and blue where it\n     understates. Justifies the price adjustment in one image. Poster caption says 3,114\n     counties, so it predates the current panel and needs rebuilding. Decide whether both\n     maps are needed or whether this one alone does the work. -->\n\n## Task groups and affordability\n:::\n\n::: {#32ac7e53 .cell .hidden execution_count=37}\n``` {.python .cell-code .hidden}\n# task-group coefficients from the panel regression (log target), with clustered SEs\npanel_coefs = model_log.params[exposure_cols_model]\npanel_se = model_log.bse[exposure_cols_model]\nmean_afford = model_df[\"affordability_salary\"].mean()\n\n# log coefficient -> % change per 1 percentage point shift -> dollar amount at panel mean\npanel_pct_per_point = (np.exp(panel_coefs / 100) - 1) * 100\npanel_dollar_per_point = (panel_pct_per_point / 100) * mean_afford\n\npanel_se_pct_per_point = (np.exp(panel_se / 100) - 1) * 100\npanel_dollar_se_per_point = (panel_se_pct_per_point / 100) * mean_afford\n\npanel_effects = pd.DataFrame({\n    \"dollar_per_point\": panel_dollar_per_point,\n    \"dollar_se_per_point\": panel_dollar_se_per_point,\n}).rename(index=label_map)\n\nlargest_group = panel_effects[\"dollar_per_point\"].idxmin()\nlargest_group_dollar = abs(panel_effects.loc[largest_group, \"dollar_per_point\"])\nlargest_group_se = panel_effects.loc[largest_group, \"dollar_se_per_point\"]\n```\n:::\n\n\n::: {#8550f4a8 .cell .hidden execution_count=38}\n``` {.python .cell-code .hidden}\nexposure_ranges = model_df[exposure_cols_model].agg([\"min\", \"max\", \"mean\", \"std\"])\ncoefs_per_point = ols_model.params[core_features] / 100  # per 1-percentage-point\n\neffects = {}\nfor col in exposure_cols_model:\n    low = exposure_ranges.loc[\"mean\", col] - exposure_ranges.loc[\"std\", col]\n    high = exposure_ranges.loc[\"mean\", col] + exposure_ranges.loc[\"std\", col]\n    range_pts = (high - low) * 100\n    effects[col] = coefs_per_point[col] * range_pts\n\neffects_series = pd.Series(effects).rename(label_map).sort_values() # this is for std bar chart if we want\n```\n:::\n\n\n:::{#272bdd39 .cell .markdown}\nThe panel regression returns a negative association between routine intensive work and\naffordability salary that holds after controls. A one percentage point shift toward\nNonroutine Manual work is associated with roughly\n\\$846 (± \\$38)\nless in affordability salary, evaluated at the panel mean.\n\n@fig-coefplot shows each task group's coefficient with its confidence interval, non\nroutine cognitive as the reference.\n\n<!-- FIGURE: fig-coefplot. NEW, poster has it as an In Progress placeholder only.\n     Coefficient plot, task group on the y axis, association with affordability salary on\n     the x axis, points with error bars, non routine cognitive as the reference. The\n     figure that turns the whole project into one number, so it carries more weight than\n     any other here. -->\n:::\n\n::: {#cell-fig-coefplot .cell execution_count=39}\n``` {.python .cell-code .hidden}\ncoefs = model_log.params[exposure_cols_model]\nci = model_log.conf_int().loc[exposure_cols_model]\nerrors = [(coefs - ci[0]).values, (ci[1] - coefs).values]\n\nfig, ax = plt.subplots(figsize=(7, 4))\nax.errorbar(coefs.rename(label_map), coefs.values, yerr=errors, fmt=\"o\", capsize=5, color=\"#4C72B0\")\nax.axhline(0, color=\"black\", linewidth=1, linestyle=\"--\")\nax.set_ylabel(\"Coefficient (log affordability salary)\")\nax.set_title(\"Task group coefficients vs. non-routine cognitive\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Task group association with affordability salary (log target), non-routine cognitive as reference. Points show coefficients; bars show 95% confidence intervals from county-clustered standard errors.](capstone_files/figure-html/fig-coefplot-output-1.png){#fig-coefplot width=703 height=346}\n:::\n:::\n\n\n:::{#bf9c6a92 .cell .markdown}\nThe associations survive the addition of poverty rate and the other baseline controls, so\nthe task groups are not standing in for poverty. @fig-coefcompare puts the coefficients\nbefore and after controls side by side.\n\n<!-- FIGURE: fig-coefcompare. NEW, poster has it as an In Progress placeholder only.\n     Paired coefficient plot or forest plot, each task group before and after adding\n     poverty and the baseline controls. Answers the objection that the task groups are\n     poverty in disguise, which the importance chart invites. -->\n:::\n\n::: {#cell-fig-coefcompare .cell execution_count=40}\n``` {.python .cell-code .hidden}\nbaseline_coefs = ols_model_base.params[exposure_cols_model]\nfull_coefs = ols_model_log.params[exposure_cols_model]\n\nx = np.arange(len(exposure_cols_model))\nwidth = 0.35\n\nfig, ax = plt.subplots(figsize=(7, 5))\nax.bar(x - width/2, baseline_coefs, width, label=\"Baseline\", color=\"#8172B2\")\nax.bar(x + width/2, full_coefs, width, label=\"With controls\", color=\"#4C72B0\")\nax.axhline(0, color=\"black\", linewidth=1)\nax.set_xticks(x)\nax.set_xticklabels([label_map.get(c, c) for c in exposure_cols_model], rotation=20, ha=\"right\")\nax.set_ylabel(\"Coefficient\")\nax.set_title(\"Task group coefficients, baseline vs. full model\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Task group coefficients before (baseline) and after (full model) adding poverty and demographic controls. Stable coefficients indicate task groups are not standing in for poverty.](capstone_files/figure-html/fig-coefcompare-output-1.png){#fig-coefcompare width=720 height=442}\n:::\n:::\n\n\n:::{#528b6320 .cell .markdown}\n## Nonlinearity\n\nThe RESET test rejects the linear specification [TK: statistic and p value], and\n@fig-binned shows why. Binned means of affordability salary across the range of routine\ncognitive work rise and then fall rather than tracking a straight line.\n\n<!-- FIGURE: fig-binned. EXISTS, poster Figure 5. Binned means of affordability salary\n     across the range of routine cognitive, actual and random forest predicted on the same\n     axes. Should port over close to as is. The residual plot that pairs with it is\n     claimed by _04 as well, resolve before building either. -->\n:::\n\n::: {#cell-fig-binned .cell execution_count=41}\n``` {.python .cell-code .hidden}\nimport matplotlib.ticker as ticker\n\ndef binned_means_plot(feature, n_bins=10):\n    plot_df = X_test.copy()\n    plot_df[\"actual\"] = y_test.values\n    plot_df[\"predicted\"] = best_rf.predict(X_test)\n    plot_df[\"bin\"] = pd.qcut(plot_df[feature], q=n_bins, duplicates=\"drop\")\n\n    binned = plot_df.groupby(\"bin\", observed=True).agg(\n        feature_mean=(feature, \"mean\"),\n        actual_mean=(\"actual\", \"mean\"),\n        predicted_mean=(\"predicted\", \"mean\"),\n    ).reset_index()\n\n    plt.figure(figsize=(6.5, 7))\n    plt.plot(binned[\"feature_mean\"], binned[\"actual_mean\"], marker=\"o\", label=\"Actual (binned mean)\")\n    plt.plot(binned[\"feature_mean\"], binned[\"predicted_mean\"], marker=\"o\", label=\"RF predicted (binned mean)\")\n    plt.xlabel(label_map.get(feature, feature))\n    plt.ylabel(\"Affordability Salary ($)\")\n    plt.title(f\"Binned means: {label_map.get(feature, feature)} vs. affordability\")\n    plt.legend(loc=\"upper center\", bbox_to_anchor=(0.5, -0.15), ncol=1)\n    plt.gca().yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f\"{int(x/1000)}k\"))\n    plt.tight_layout()\n    plt.subplots_adjust(bottom=0.28)\n    plt.show()\n\nbinned_means_plot(\"routine_cognitive_share\")\n```\n\n::: {.cell-output .cell-output-display}\n![Binned means of affordability salary across routine cognitive employment share, actual vs. Random Forest predicted. The non-monotonic pattern is what a linear model cannot represent.](capstone_files/figure-html/fig-binned-output-1.png){#fig-binned width=681 height=639}\n:::\n:::\n\n\n:::{#b3769ff2 .cell .markdown}\n@fig-modelcomp compares held out performance across specifications. The random forest\nreaches a test R² of 0\\.877\nagainst 0\\.896\nfor the log-target linear model, and 0\\.873\nfor the neural network. The gap is evidence\nthat the relationship has curvature the linear model cannot represent, which is the same\nconclusion the RESET test reaches by a different route.\n\n<!-- FIGURE: fig-modelcomp. EXISTS, poster Figure 3. Bar chart of held out test R squared\n     for OLS, ridge, random forest, neural net, showing 0.610, 0.610, 0.840, 0.739.\n     Poster draft 4 floats merging this with the binned means into one progression figure,\n     which would make it NEW. Decide before building. -->\n:::\n\n::: {#cell-fig-modelcomp .cell execution_count=42}\n``` {.python .cell-code .hidden}\ndisplay_labels = {\n    \"OLS (log target)\": \"Linear Model\",\n    \"Random Forest (log target)\": \"Random Forest\",\n    \"Neural Net\": \"Neural Network\",\n}\nchart_labels = results[\"model\"].map(display_labels)\n\nplt.figure(figsize=(7, 5))\ncolors = [\"#4C72B0\", \"#55A868\", \"#C44E52\"]\nbars = plt.bar(chart_labels, results[\"test_r2\"], color=colors)\nplt.ylabel(\"Test R²\")\nplt.title(\"Model comparison — held-out test R²\")\nplt.ylim(0, 1)\nfor bar, val in zip(bars, results[\"test_r2\"]):\n    plt.text(bar.get_x() + bar.get_width() / 2, val + 0.01, f\"{val:.3f}\", ha=\"center\", fontsize=20)\nplt.xticks(rotation=20, ha=\"right\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Held-out test R² across three model specifications. Random Forest and the log-target linear model perform comparably; both outperform the neural net.](capstone_files/figure-html/fig-modelcomp-output-1.png){#fig-modelcomp width=634 height=442}\n:::\n:::\n\n\n:::{#fbe21e6f .cell .markdown}\n## What matters most\n\nPoverty rate is the strongest single feature in the random forest, by a wide margin\n(@fig-importance). Task groups follow, with non routine manual ranked highest among them.\nThis ordering is consistent with the regression: poverty carries most of the explanatory\nweight, and the task groups add to it rather than substituting for it.\n\n<!-- FIGURE: fig-importance. EXISTS, poster Figure 6. Feature importance, horizontal\n     bars, mean drop in test R squared when shuffled, ordered poverty rate, routine\n     cognitive, non routine manual, unemployment, routine manual. Note the poster titles\n     it \"permutation importance\", change to feature importance when porting. -->\n:::\n\n::: {#fig-importance .cell execution_count=43}\n``` {.python .cell-code .hidden}\n# perm_series = pd.Series(perm_imp.importances_mean, index=feature_cols_reg)[core_features].rename(label_map)\n# perm_series[\"Year (grouped)\"] = year_drop\n# perm_series[\"State (grouped)\"] = state_drop\n# perm_series = perm_series.sort_values()\n\n# plt.figure(figsize=(5.7, 5))\n# plt.barh(perm_series.index, perm_series.values, color=\"#4C72B0\")\n# plt.xlabel(\"Importance to prediction accuracy\")\n# plt.suptitle(\"Random Forest permutation importance\", fontsize=20, y=0.96)\n# plt.subplots_adjust(top=0.88, bottom=0.18)\n# plt.show()\n```\n:::\n\n\n:::{#67c0a95d .cell .markdown}\nAs shown in @fig-importance, permutation importance for\n`poverty_rate` at 0.625 is overwhelmingly the\nlargest number here, which is consistent with every model's findings so far.\n`non_routine_manual_share` is the highest of our task-mix categories, with\n`routine_manual_share` next, and `routine_cognitive_share` last.\n\n<!-- FIGURE: fig-pdp. NEW, poster has it as an In Progress placeholder only. Partial\n     dependence for the task groups. Chris to supply. Also referenced from _04, pick one\n     home. -->\n:::\n\n::: {#cell-fig-pdp .cell execution_count=44}\n``` {.python .cell-code .hidden}\nfrom sklearn.inspection import PartialDependenceDisplay\n\nfig, ax = plt.subplots(figsize=(9, 4))\ndisplay = PartialDependenceDisplay.from_estimator(\n    best_rf, X_test, features=exposure_cols_model,\n    ax=ax,\n)\n\nfor axis, col in zip(display.axes_.ravel(), exposure_cols_model):\n    axis.set_xlabel(label_map.get(col, col))\n    \nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Partial dependence of predicted affordability salary (raw dollars) on each task group's employment share, holding other features at their observed distribution.](capstone_files/figure-html/fig-pdp-output-1.png){#fig-pdp width=826 height=346}\n:::\n:::\n\n\n:::{#c5d73930 .cell .markdown}\n## Stability over time\n\nA county's task mix moves very little across the fifteen year panel [TK: quantify]. This\nmatters for interpretation. Because the mix is close to a fixed characteristic of place,\nthe affordability differences associated with it do not fade, and they are not something\nresidents can be expected to move out from under.\n\n<!-- FIGURE: fig-stability. NEW, poster has it as an In Progress placeholder only.\n     Stacked area chart, year on the x axis, share of total task weight on the y axis,\n     four bands. Shows the mix holds steady across the panel. Carries the persistence\n     claim the conclusions lean on, so it should not stay as a sentence. -->\n\n## Robustness\n\nRestricting the panel to 2010 onward, which removes the occupation coding change described\nin @sec-data, leaves the main associations intact [TK: report the restricted estimates].\n\n<!--\nTODO results\n\nWhat this section is for:\n\n1. If it can be shown visually, show it. Prefer figures to tables and to in text\n   description.\n2. Every figure stands on its own. A reader who has not read the rest of the paper\n   should get it from the figure and its caption alone.\n3. One idea per figure. If two figures overlap, cut one or combine them into panels.\n4. Storyboard. Arrange the figures in the order that tells the story, then write to\n   them. Rearrange freely until the sequence holds together.\n5. Open by hitting the highlights of the figures. Do not recapitulate them. The text is\n   complementary to the figures, not a transcript of them.\n6. Use the remaining text for what no figure carries.\n7. Tables only if a figure cannot do it, and then keep them small.\n\nComplete:\n\n- the 1,041 figure, its sign, standard error, and which group carries the largest\n  coefficient (now computed automatically from model_log as panel_effects/largest_group)\n- test R squared for all three models (ridge dropped; OLS, Random Forest, and neural\n  net R squared now pulled directly from the results dataframe rather than hardcoded)\n- resolve the two figures claimed by both this section and _04: the residual plot stays\n  in _04 only, feature importance stays here only as fig-importance\n- captions are self contained, stating units and what the axes are, not just naming\n  the figure\n\nStill to do:\n\n- remaining numbers in prose (RESET test statistic and p value) are still unconfirmed,\n  check against the current model run\n- quantify how little the task mix moves\n- restricted 2010 onward estimates, and decide whether they live here or in _04\n- ten figures are referenced. Five exist in some form on the poster (fig-affordmap,\n  fig-gapmap, fig-binned, fig-modelcomp, fig-importance) and five are new\n  (fig-coefplot, fig-coefcompare, fig-pdp, fig-stability, and the residual plot). Under\n  rule 3 ten is too many. Storyboard and cut, most likely candidates are one of the two\n  choropleths and merging the binned means with the model comparison\n- the poster figures were built on the old full frame, all need rebuilding on the 848\n  county panel before the numbers in the text can be trusted\n-->\n\n# Conclusions {#sec-conclusions}\n\n## Summary\n\nWe asked whether counties with more automatable work are less affordable for the people\nwho live in them. Building a county by year panel from eight federal sources, summarizing\neach county's work by four task groups, and measuring affordability as median household\nincome adjusted for local prices, we find that the answer is yes and that the relationship\nholds once poverty and unemployment are accounted for. Poverty is by a wide margin the\nstrongest single correlate of county affordability. The task mix is a smaller but separate\none.\n\n## What this adds\n\nTwo patterns are worth stating plainly before the broader claim. Poverty is the strongest\nsingle correlate of county affordability, but the task mix relates to affordability\nindependently of it. And neither relationship is a straight line: routine cognitive work\nshows a rise then fall pattern, and poverty's association is steepest at low levels and\nflattens at high ones.\n\nThe task framework has been applied to wages and to employment composition, mostly at the\nnational or commuting zone level. Applying it to a cost adjusted outcome at the county\nlevel changes what the measure describes: not what work pays, but what that pay buys where\nit is earned. Two findings follow from that shift. The association is present after\ncontrolling for local economic distress, so it is not poverty in different clothing. And\nit is not linear, which the RESET test establishes and the flexible models exploit, so\nstudies that assume a straight line relationship between task composition and local\noutcomes are leaving structure on the table.\n\nThe finding lands on people through place. Residents of routine work counties see their\nincomes buy systematically less, and because a county's task mix barely moves across\nfifteen years, the difference is built into where they live rather than something\nindividual effort resolves. Three groups can act on that. Economic development agencies\ndeciding where workforce training goes, since the task mix separates structurally exposed\ncounties from those in a temporary downturn. Policymakers and planners designing cost of\nliving responses, since these gaps will not close on their own. And researchers extending\nthe framework, since both the county level link and its nonlinear shape point past\nexisting national wage studies.\n\n## Limitations\n\nThe results are associational. Counties are not assigned their mix of work, and nothing in\nthis design isolates a causal channel, so we cannot say that automatable work makes a\nplace less affordable, only that the two move together.\n\nThe four task groups are parts of a whole and sum to one, so one had to serve as a\nreference category. Every coefficient is read relative to non routine cognitive work\nrather than in isolation.\n\nCoverage is the sharpest constraint. Task group values exist for 12,087 of the 47,340\ncounty year combinations in the frame, and dropping the 104 rows missing an unemployment\nrate leaves 11,983 for estimation across 848 counties. The counties that fall out are\nsmall ones, below the population threshold at which the American Community Survey\npublishes one year occupational estimates, so the panel describes metropolitan and larger\nnon metropolitan counties rather than the country.\n\nRegional Price Parities are published for metropolitan areas, so counties outside one take\ntheir state value. Roughly 55 percent of county year rows use that fallback, which applies\na single price index to counties whose actual price levels differ, and it falls\ndisproportionately on rural places.\n\n2020 is excluded because the American Community Survey did not release one year estimates\nfor it. The 2009 to 2010 occupation coding change is a source artifact that inflates\nmeasured within county variance for routine cognitive work; restricting to 2010 onward\nleaves the conclusions unchanged.\n\nThe machine learning results rest on a single train and test split [TK: replace with cross\nvalidation if time allows].\n\n## Ethical considerations\n\nAll data are public county level aggregates with no individual records, so no person can\nbe identified. Two harms are worth naming. Labeling counties as exposed or stuck could\nstigmatize them or steer investment away from the places that need it. And reading the\nassociation as causal could motivate policy that tries to reshape a county's mix of work\nin the expectation that affordability follows, which this study does not support.\n\n## Future directions\n\nTwo extensions would address the limitations above directly.\n\nThe coverage gap could be narrowed with satellite imagery. @Jean2016 estimate local\neconomic conditions from daytime and nighttime imagery where survey data are thin, an\napproach that could recover the small counties this panel excludes and allow the\naffordability pattern to be retested on them.\n\nFiner grained labor data would move the work closer to a causal claim. Splitting the task\nmix by worker education and status would separate the effect of workforce composition from\nthe effect of the task mix itself, which the current design cannot disentangle.\n\n## Conclusion\n\n[TK: the closing paragraph. Zelner's fourth move, the one that ties it together. What does\nit all mean, why does it matter, what sticks with the reader. This is the place to be a\nlittle more opinionated. Draft line to work from: poverty remains the strongest correlate\nof county affordability, but the mix of work a county holds is a separate pressure on top\nof it, and poverty and unemployment statistics alone do not capture the full picture of\naffordability risk.]\n\n<!--\nTODO conclusions\n\nWhat this section is for:\n\n1. Summarize. A reader who opened straight to this paragraph should learn what we did.\n2. Sell the product. The affirmative case. Why the approach suited the question, which\n   gap from the background it closes. No need to be negative about other work.\n3. Limitations, then future directions. Limitations are stopping points that mark the\n   boundary of the analysis, not an undermining of it. A well written limitations\n   paragraph adds credibility. Future directions is where to plant a flag on what comes\n   next.\n4. Conclusion. Tie it together, say why it matters, be a little more opinionated.\n\nIMPORTANT TO NOTE: do not claim more than the analysis supports, and do not narrate the\nprocess or dead ends.\n\nStructural questions still open:\n\n- move 4 is missing, the section currently ends on future work. TK placeholder added\n- ethics sits between limitations and future directions, which breaks Zelner's order.\n  Either move it before limitations or into _01. The poster puts it in the intro panel\n- \"What this adds\" now opens with the two discussion bullets and then makes the\n  contribution argument, so it does two jobs. Consider splitting or trimming\n- the first paragraph of \"What this adds\" repeats the poverty point from the summary\n\nContent still to do:\n\n- keep the limitations list in sync with whatever _05 ends up reporting\n- the nonlinearity claim about poverty tapering at high levels comes from the poster\n  partial dependence, confirm it holds in the current run before stating it\n-->\n\n# References\n\n:::{#refs}\n:::\n:::\n\n",
    "supporting": [
      "capstone_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}